### ISSUE TITLE
lxk0301大佬好像已经开放jd_scripts,但jd-base还是无法更新js文件

### ISSUE THREAD

**Issue by leifengwl** [dockere/jd-base#101]
jd-base已经更新到目前最新的文件，也就是两小时前的，但更新jd_scripts时依旧提示错误Access deined: DeployKey not enabled，是还没有密钥吗？

**Comment by dockere** [comment]
映射目录了吧？删掉重新拉取就好了。

**Comment by leifengwl** [comment]
> 映射目录了吧？删除掉重新拉取就好了。

是的  我已经删掉并重新拉取了  已经可以更新了 谢谢大佬
