### ISSUE TITLE
py镜像无法拉取代码

### ISSUE THREAD

**Issue by vale8023** [dockere/jd-base#102]
![image](https://user-images.githubusercontent.com/35561410/112917426-2b426d80-9135-11eb-8ed0-4f839bf9c601.png)

**Comment by dockere** [comment]
lxk删秘钥了，要删除映射目录后，更新镜像了

**Comment by Woody-Wan** [comment]
难定，希望大佬可以更新教程了

**Comment by blucewyan** [comment]
> lxk删秘钥了，要删除映射目录后，更新镜像了

我重新建了一个空白镜像  用的noobx/jd:py  也是拉取不了脚本，也是出现那个红字

**Comment by vale8023** [comment]
> > lxk删秘钥了，要删除映射目录后，更新镜像了
> 
> 我重新建了一个空白镜像 用的noobx/jd:py 也是拉取不了脚本，也是出现那个红字
> 
> 我看TAG：gitee里面也有PY的脚本了 是不是以后就用gitee 就可以了

我删除本地镜像，删除映射目录，重新拉镜像，然后就好了。

**Comment by blucewyan** [comment]
> > > lxk删秘钥了，要删除映射目录后，更新镜像了
> > 
> > 
> > 我重新建了一个空白镜像 用的noobx/jd:py 也是拉取不了脚本，也是出现那个红字
> > 我看TAG：gitee里面也有PY的脚本了 是不是以后就用gitee 就可以了
> 
> 我删除本地镜像，删除映射目录，重新拉镜像，然后就好了。
那估计是我没有删除本地镜像的原因

用的PY还是gitee   gitee里面好像也支持python了
