### ISSUE TITLE
请问大佬怎么永久禁用Crazy Joy Coin的挂机程序呀？

### ISSUE THREAD

**Issue by bcbcd666234** [dockere/jd-base#104]
不想挂机Crazy Joy Coin了，又没有分红joy,有了也要拉人头，挂着占资源还费电，决定放弃。但我只知道停用脚本，但是每次自动更新docker它又重启了。想问一下有永久禁用的命令吗？

**Comment by dockere** [comment]
-e ENABLE_HANGUP=false \

**Comment by bcbcd666234** [comment]
本来想问在不删docker的情况下怎么设置的，刚刚重装禁用挂机了。感谢大佬回复

**Comment by kissfast** [comment]
> -e ENABLE_HANGUP=false \

直接在config里面加入这一行就可以了吧？
ENABLE_HANGUP=false

**Comment by dockere** [comment]
> > -e ENABLE_HANGUP=false \
> 
> 直接在config里面加入这一行就可以了吧？
> ENABLE_HANGUP=false

是的
