### ISSUE TITLE
请问大佬您的主项目noobx/jd:gitee镜像带有py功能吗？

### ISSUE THREAD

**Issue by donggua1118** [dockere/jd-base#105]
一直用您的副项目，py很是全面，这次由于不能更新脚本，重新安装的话想试试您的主项目，想问下您，主项目可否运行py？

**Comment by dockere** [comment]
不支持。只有node环境

**Comment by donggua1118** [comment]
感谢老大，那还是继续用您的副项目吧，想要更新pull，只能删除映射文件，重新走一遍安装吗？

**Comment by dockere** [comment]
是的啊，不然拉取不到lxk脚本

**Comment by donggua1118** [comment]
感谢大佬 ，您的项目很棒，支持您！！！
