### ISSUE TITLE
到挂机程序后，容器反复重启，怎么解决

### ISSUE THREAD

**Issue by LingFeng0918** [dockere/jd-base#106]
========================3. 启动挂机程序========================

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Flushing /root/.pm2/pm2.log
[PM2] Logs flushed
Use --update-env to update environment variables

**Comment by dockere** [comment]
没有成功启动挂机会导致容器无限重启，可能地区网络没有安装好依赖原因，请更新下镜像。
