### ISSUE TITLE
Version: v3.31.6这是最新版麻?

### ISSUE THREAD

**Issue by zzw2016** [dockere/jd-base#108]

**Comment by UMRQWQ** [comment]
3.32.1

**Comment by zzw2016** [comment]
> 3.32.1

更新命令是多少?我一直都是3.31.6,求告知

**Comment by dockere** [comment]
> > 3.32.1
> 
> 更新命令是多少?我一直都是3.31.6,求告知

重装删掉重新安装，这版本已经无法拉取lxk脚本了，密钥变更了

**Comment by zzw2016** [comment]
> > > 3.32.1
> > 
> > 
> > 更新命令是多少?我一直都是3.31.6,求告知
> 
> 重装删掉重新安装，如有映射目录要删除映射目录，这版本已经无法拉取lxk脚本了，密钥变更了

配置需要备份吧?

**Comment by dockere** [comment]
这个随你了
