### ISSUE TITLE
修改docker映射目录后无法访问

### ISSUE THREAD

**Issue by UMRQWQ** [dockere/jd-base#109]
大佬看我的蜜汁操作，求解答

我在创建的时候没用映射scripts和panel目录，然后我把docker停止后，修改了config.v2.json里面的映射目录，然后启动docker，项目就变成了网址出错，然后我装有portainer，通过它，我把镜像还有容器都删除了，再通过创建容器的命令，这次加上了那两个路径，然后访问IP：5678提示500 Internal Privoxy Error的报错，我在portainer中看到容器是在运行着的，现在我不知道是什么原因了，求大佬帮助！

**Comment by UMRQWQ** [comment]
现在把容器和镜像全删掉  用基本的这个也是500错误了  端口都是开着的

**Comment by UMRQWQ** [comment]
,========================1. 更新源代码========================
,
,crond[7]: crond (busybox 1.31.1) started, log level 8
,
,--------------------------------------------------------------
,
,系统时间：2021-04-01 18:25:04
,
,SHELL脚本目录：/jd
,
,JS脚本目录：/jd/scripts
,
,--------------------------------------------------------------
,
,更新shell脚本，原地址：https://gitee.com/dockere/jd-base
,
,Fetching origin
,HEAD is now at b57dd85 change
,
,shell脚本更新完成...
,
,更新lxk0301脚本，原地址：https://gitee.com/lxk0301/jd_docker
,
,Fetching origin
,HEAD is now at 53a336a fix
,
,js脚本更新完成...
,
,
,========================2. 检测配置文件========================
,
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,
,成功添加定时任务...
,
,========================3. 启动挂机程序========================
,
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,[PM2] PM2 Successfully daemonized
,[PM2] Flushing /root/.pm2/pm2.log
,[PM2] Logs flushed
,Use --update-env to update environment variables
,[PM2] Starting /jd/scripts/jd_crazy_joy_coin.js in fork_mode (1 instance)
,[PM2] Done.
,┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
,│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
,├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
,│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 139      │ 0s     │ 0    │ online    │ 0%       │ 20.7mb   │ root     │ disabled │
,└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
,挂机程序启动成功...
,
,========================4. 启动控制面板========================
,
,[PM2] Starting /jd/panel/server.js in fork_mode (1 instance)
,[PM2] Done.
,┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
,│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
,├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
,│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 139      │ 0s     │ 0    │ online    │ 66.7%    │ 28.5mb   │ root     │ disabled │
,│ 1   │ server               │ default     │ N/A     │ fork    │ 160      │ 0s     │ 0    │ online    │ 0%       │ 7.4mb    │ root     │ disabled │
,└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
,控制面板启动成功...
,
,如未修改用户名密码，则初始用户名为：admin，初始密码为：adminadmin
,
,请访问 http://<ip>:5678 登陆并修改配置...
,
,容器启动成功...
,
,Welcome to Node.js v15.9.0.
,Type ".help" for more information.
,

**Comment by UMRQWQ** [comment]
以上是我看到的容器启动日志，可是就是访问不了，提示您访问的网页出错了

**Comment by UMRQWQ** [comment]
以上日志不对 我怀疑是残留，在我把映射出来的jd文件夹删除后重新创建容器出现了下面的日志


,========================1. 更新源代码========================
,
,crond[9]: crond (busybox 1.31.1) started, log level 8
,
,--------------------------------------------------------------
,
,系统时间：2021-04-01 18:40:02
,
,SHELL脚本目录：/jd
,
,JS脚本目录：/jd/scripts
,
,--------------------------------------------------------------
,
,更新shell脚本，原地址：https://gitee.com/dockere/jd-base
,
,Fetching origin
,HEAD is now at b57dd85 change
,
,shell脚本更新完成...
,
,Cloning into '/jd/scripts'...
,Warning: Permanently added the ECDSA host key for IP address '180.97.125.228' to the list of known hosts.

,remote: Enumerating objects: 8977, done.
,remote: Counting objects:   0% (1/8977)
remote: Counting objects:   1% (90/8977)
remote: Counting objects:   2% (180/8977)
remote: Counting objects:   3% (270/8977)
remote: Counting objects:   4% (360/8977)
remote: Counting objects:   5% (449/8977)
remote: Counting objects:   6% (539/8977)
remote: Counting objects:   7% (629/8977)
remote: Counting objects:   8% (719/8977)
remote: Counting objects:   9% (808/8977)
remote: Counting objects:  10% (898/8977)
remote: Counting objects:  11% (988/8977)
remote: Counting objects:  12% (1078/8977)
remote: Counting objects:  13% (1168/8977)
remote: Counting objects:  14% (1257/8977)
remote: Counting objects:  15% (1347/8977)
remote: Counting objects:  16% (1437/8977)
remote: Counting objects:  17% (1527/8977)
remote: Counting objects:  18% (1616/8977)
remote: Counting objects:  19% (1706/8977)
remote: Counting objects:  20% (1796/8977)
remote: Counting objects:  21% (1886/8977)
remote: Counting objects:  22% (1975/8977)
remote: Counting objects:  23% (2065/8977)
remote: Counting objects:  24% (2155/8977)
remote: Counting objects:  25% (2245/8977)
remote: Counting objects:  26% (2335/8977)
remote: Counting objects:  27% (2424/8977)
remote: Counting objects:  28% (2514/8977)
remote: Counting objects:  29% (2604/8977)
remote: Counting objects:  30% (2694/8977)
remote: Counting objects:  31% (2783/8977)
remote: Counting objects:  32% (2873/8977)
remote: Counting objects:  33% (2963/8977)
remote: Counting objects:  34% (3053/8977)
remote: Counting objects:  35% (3142/8977)
remote: Counting objects:  36% (3232/8977)
remote: Counting objects:  37% (3322/8977)
remote: Counting objects:  38% (3412/8977)
remote: Counting objects:  39% (3502/8977)
remote: Counting objects:  40% (3591/8977)
remote: Counting objects:  41% (3681/8977)
remote: Counting objects:  42% (3771/8977)
remote: Counting objects:  43% (3861/8977)
remote: Counting objects:  44% (3950/8977)
remote: Counting objects:  45% (4040/8977)
remote: Counting objects:  46% (4130/8977)
remote: Counting objects:  47% (4220/8977)
remote: Counting objects:  48% (4309/8977)
remote: Counting objects:  49% (4399/8977)
remote: Counting objects:  50% (4489/8977)
remote: Counting objects:  51% (4579/8977)
remote: Counting objects:  52% (4669/8977)
remote: Counting objects:  53% (4758/8977)
remote: Counting objects:  54% (4848/8977)
remote: Counting objects:  55% (4938/8977)
remote: Counting objects:  56% (5028/8977)
remote: Counting objects:  57% (5117/8977)
remote: Counting objects:  58% (5207/8977)
remote: Counting objects:  59% (5297/8977)
remote: Counting objects:  60% (5387/8977)
remote: Counting objects:  61% (5476/8977)
remote: Counting objects:  62% (5566/8977)
remote: Counting objects:  63% (5656/8977)
remote: Counting objects:  64% (5746/8977)
remote: Counting objects:  65% (5836/8977)
remote: Counting objects:  66% (5925/8977)
remote: Counting objects:  67% (6015/8977)
remote: Counting objects:  68% (6105/8977)
remote: Counting objects:  69% (6195/8977)
remote: Counting objects:  70% (6284/8977)
remote: Counting objects:  71% (6374/8977)
remote: Counting objects:  72% (6464/8977)
remote: Counting objects:  73% (6554/8977)
remote: Counting objects:  74% (6643/8977)
remote: Counting objects:  75% (6733/8977)
remote: Counting objects:  76% (6823/8977)
remote: Counting objects:  77% (6913/8977)
remote: Counting objects:  78% (7003/8977)
remote: Counting objects:  79% (7092/8977)
remote: Counting objects:  80% (7182/8977)
remote: Counting objects:  81% (7272/8977)
remote: Counting objects:  82% (7362/8977)
remote: Counting objects:  83% (7451/8977)
remote: Counting objects:  84% (7541/8977)
remote: Counting objects:  85% (7631/8977)
remote: Counting objects:  86% (7721/8977)
remote: Counting objects:  87% (7810/8977)
remote: Counting objects:  88% (7900/8977)
remote: Counting objects:  89% (7990/8977)
remote: Counting objects:  90% (8080/8977)
remote: Counting objects:  91% (8170/8977)
remote: Counting objects:  92% (8259/8977)
remote: Counting objects:  93% (8349/8977)
remote: Counting objects:  94% (8439/8977)
remote: Counting objects:  95% (8529/8977)
remote: Counting objects:  96% (8618/8977)
remote: Counting objects:  97% (8708/8977)
remote: Counting objects:  98% (8798/8977)
remote: Counting objects:  99% (8888/8977)
remote: Counting objects: 100% (8977/8977)
remote: Counting objects: 100% (8977/8977), done.
,remote: Compressing objects:   0% (1/3323)
remote: Compressing objects:   1% (34/3323)
remote: Compressing objects:   2% (67/3323)
remote: Compressing objects:   3% (100/3323)
remote: Compressing objects:   4% (133/3323)
remote: Compressing objects:   5% (167/3323)
remote: Compressing objects:   6% (200/3323)
remote: Compressing objects:   7% (233/3323)
remote: Compressing objects:   8% (266/3323)
remote: Compressing objects:   9% (300/3323)
remote: Compressing objects:  10% (333/3323)
remote: Compressing objects:  11% (366/3323)
remote: Compressing objects:  12% (399/3323)
remote: Compressing objects:  13% (432/3323)
remote: Compressing objects:  14% (466/3323)
remote: Compressing objects:  15% (499/3323)
remote: Compressing objects:  16% (532/3323)
remote: Compressing objects:  17% (565/3323)
remote: Compressing objects:  18% (599/3323)
remote: Compressing objects:  19% (632/3323)
remote: Compressing objects:  20% (665/3323)
remote: Compressing objects:  21% (698/3323)
remote: Compressing objects:  22% (732/3323)
remote: Compressing objects:  23% (765/3323)
remote: Compressing objects:  24% (798/3323)
remote: Compressing objects:  25% (831/3323)
remote: Compressing objects:  26% (864/3323)
remote: Compressing objects:  27% (898/3323)
remote: Compressing objects:  28% (931/3323)
remote: Compressing objects:  29% (964/3323)
remote: Compressing objects:  30% (997/3323)
remote: Compressing objects:  31% (1031/3323)
remote: Compressing objects:  32% (1064/3323)
remote: Compressing objects:  33% (1097/3323)
remote: Compressing objects:  34% (1130/3323)
remote: Compressing objects:  35% (1164/3323)
remote: Compressing objects:  36% (1197/3323)
remote: Compressing objects:  37% (1230/3323)
remote: Compressing objects:  38% (1263/3323)
remote: Compressing objects:  39% (1296/3323)
remote: Compressing objects:  40% (1330/3323)
remote: Compressing objects:  41% (1363/3323)
remote: Compressing objects:  42% (1396/3323)
remote: Compressing objects:  43% (1429/3323)
remote: Compressing objects:  44% (1463/3323)
remote: Compressing objects:  45% (1496/3323)
remote: Compressing objects:  46% (1529/3323)
remote: Compressing objects:  47% (1562/3323)
remote: Compressing objects:  48% (1596/3323)
remote: Compressing objects:  49% (1629/3323)
remote: Compressing objects:  50% (1662/3323)
remote: Compressing objects:  51% (1695/3323)
remote: Compressing objects:  52% (1728/3323)
remote: Compressing objects:  53% (1762/3323)
remote: Compressing objects:  54% (1795/3323)
remote: Compressing objects:  55% (1828/3323)
remote: Compressing objects:  56% (1861/3323)
remote: Compressing objects:  57% (1895/3323)
remote: Compressing objects:  58% (1928/3323)
remote: Compressing objects:  59% (1961/3323)
remote: Compressing objects:  60% (1994/3323)
remote: Compressing objects:  61% (2028/3323)
remote: Compressing objects:  62% (2061/3323)
remote: Compressing objects:  63% (2094/3323)
remote: Compressing objects:  64% (2127/3323)
remote: Compressing objects:  65% (2160/3323)
remote: Compressing objects:  66% (2194/3323)
remote: Compressing objects:  67% (2227/3323)
remote: Compressing objects:  68% (2260/3323)
remote: Compressing objects:  69% (2293/3323)
remote: Compressing objects:  70% (2327/3323)
remote: Compressing objects:  71% (2360/3323)
remote: Compressing objects:  72% (2393/3323)
remote: Compressing objects:  73% (2426/3323)
remote: Compressing objects:  74% (2460/3323)
remote: Compressing objects:  75% (2493/3323)
remote: Compressing objects:  76% (2526/3323)
remote: Compressing objects:  77% (2559/3323)
remote: Compressing objects:  78% (2592/3323)
remote: Compressing objects:  79% (2626/3323)
remote: Compressing objects:  80% (2659/3323)
remote: Compressing objects:  81% (2692/3323)
remote: Compressing objects:  82% (2725/3323)
remote: Compressing objects:  83% (2759/3323)
remote: Compressing objects:  84% (2792/3323)
remote: Compressing objects:  85% (2825/3323)
remote: Compressing objects:  86% (2858/3323)
remote: Compressing objects:  87% (2892/3323)
remote: Compressing objects:  88% (2925/3323)
remote: Compressing objects:  89% (2958/3323)
remote: Compressing objects:  90% (2991/3323)
remote: Compressing objects:  91% (3024/3323)
remote: Compressing objects:  92% (3058/3323)
remote: Compressing objects:  93% (3091/3323)
remote: Compressing objects:  94% (3124/3323)
remote: Compressing objects:  95% (3157/3323)
remote: Compressing objects:  96% (3191/3323)
remote: Compressing objects:  97% (3224/3323)
remote: Compressing objects:  98% (3257/3323)
remote: Compressing objects:  99% (3290/3323)
remote: Compressing objects: 100% (3323/3323)
remote: Compressing objects: 100% (3323/3323), done.
,Receiving objects:   0% (1/11796)
Receiving objects:   1% (118/11796)
Receiving objects:   2% (236/11796)
Receiving objects:   3% (354/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:   4% (472/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:   5% (590/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:   6% (708/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:   7% (826/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:   8% (944/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:   9% (1062/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:  10% (1180/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:  11% (1298/11796), 1.58 MiB | 3.14 MiB/s
Receiving objects:  11% (1312/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  12% (1416/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  13% (1534/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  14% (1652/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  15% (1770/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  16% (1888/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  17% (2006/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  18% (2124/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  19% (2242/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  20% (2360/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  21% (2478/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  22% (2596/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  23% (2714/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  24% (2832/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  25% (2949/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  26% (3067/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  27% (3185/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  28% (3303/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  29% (3421/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  30% (3539/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  31% (3657/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  32% (3775/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  33% (3893/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  34% (4011/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  35% (4129/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  36% (4247/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  37% (4365/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  38% (4483/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  39% (4601/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  40% (4719/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  41% (4837/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  42% (4955/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  43% (5073/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  44% (5191/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  45% (5309/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  46% (5427/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  47% (5545/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  48% (5663/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  49% (5781/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  50% (5898/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  51% (6016/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  52% (6134/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  53% (6252/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  54% (6370/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  55% (6488/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  56% (6606/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  57% (6724/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  58% (6842/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  59% (6960/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  60% (7078/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  61% (7196/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  62% (7314/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  63% (7432/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  64% (7550/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  65% (7668/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  66% (7786/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  67% (7904/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  68% (8022/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  69% (8140/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  70% (8258/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  71% (8376/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  72% (8494/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  73% (8612/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  74% (8730/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  75% (8847/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  76% (8965/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  77% (9083/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  78% (9201/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  79% (9319/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  80% (9437/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  81% (9555/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  82% (9673/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  83% (9791/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  84% (9909/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  85% (10027/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  86% (10145/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  87% (10263/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  88% (10381/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  89% (10499/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  90% (10617/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  91% (10735/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  92% (10853/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  93% (10971/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  94% (11089/11796), 5.45 MiB | 5.44 MiB/s
remote: Total 11796 (delta 5813), reused 8611 (delta 5580), pack-reused 2819
,Receiving objects:  95% (11207/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  96% (11325/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  97% (11443/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  98% (11561/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects:  99% (11679/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects: 100% (11796/11796), 5.45 MiB | 5.44 MiB/s
Receiving objects: 100% (11796/11796), 12.20 MiB | 8.80 MiB/s, done.
,Resolving deltas:   0% (0/8167)
Resolving deltas:   1% (115/8167)
Resolving deltas:   2% (213/8167)
Resolving deltas:   3% (264/8167)
Resolving deltas:   5% (421/8167)
Resolving deltas:   7% (599/8167)
Resolving deltas:   9% (816/8167)
Resolving deltas:  11% (966/8167)
Resolving deltas:  12% (1059/8167)
Resolving deltas:  14% (1184/8167)
Resolving deltas:  15% (1263/8167)
Resolving deltas:  16% (1344/8167)
Resolving deltas:  17% (1389/8167)
Resolving deltas:  18% (1473/8167)
Resolving deltas:  19% (1621/8167)
Resolving deltas:  20% (1640/8167)
Resolving deltas:  21% (1793/8167)
Resolving deltas:  22% (1808/8167)
Resolving deltas:  23% (1926/8167)
Resolving deltas:  24% (1961/8167)
Resolving deltas:  25% (2059/8167)
Resolving deltas:  26% (2124/8167)
Resolving deltas:  27% (2213/8167)
Resolving deltas:  28% (2291/8167)
Resolving deltas:  29% (2419/8167)
Resolving deltas:  31% (2578/8167)
Resolving deltas:  32% (2646/8167)
Resolving deltas:  33% (2733/8167)
Resolving deltas:  37% (3031/8167)
Resolving deltas:  40% (3282/8167)
Resolving deltas:  41% (3381/8167)
Resolving deltas:  42% (3476/8167)
Resolving deltas:  43% (3524/8167)
Resolving deltas:  44% (3594/8167)
Resolving deltas:  45% (3676/8167)
Resolving deltas:  46% (3757/8167)
Resolving deltas:  47% (3839/8167)
Resolving deltas:  48% (3921/8167)
Resolving deltas:  49% (4002/8167)
Resolving deltas:  50% (4084/8167)
Resolving deltas:  51% (4166/8167)
Resolving deltas:  52% (4247/8167)
Resolving deltas:  53% (4329/8167)
Resolving deltas:  54% (4411/8167)
Resolving deltas:  55% (4492/8167)
Resolving deltas:  56% (4575/8167)
Resolving deltas:  57% (4656/8167)
Resolving deltas:  58% (4738/8167)
Resolving deltas:  59% (4819/8167)
Resolving deltas:  60% (4901/8167)
Resolving deltas:  61% (4982/8167)
Resolving deltas:  62% (5106/8167)
Resolving deltas:  63% (5169/8167)
Resolving deltas:  64% (5228/8167)
Resolving deltas:  65% (5319/8167)
Resolving deltas:  66% (5395/8167)
Resolving deltas:  67% (5486/8167)
Resolving deltas:  68% (5556/8167)
Resolving deltas:  69% (5639/8167)
Resolving deltas:  70% (5738/8167)
Resolving deltas:  71% (5836/8167)
Resolving deltas:  72% (5886/8167)
Resolving deltas:  73% (6016/8167)
Resolving deltas:  74% (6044/8167)
Resolving deltas:  75% (6175/8167)
Resolving deltas:  76% (6212/8167)
Resolving deltas:  77% (6298/8167)
Resolving deltas:  78% (6379/8167)
Resolving deltas:  79% (6469/8167)
Resolving deltas:  80% (6554/8167)
Resolving deltas:  81% (6616/8167)
Resolving deltas:  82% (6699/8167)
Resolving deltas:  83% (6789/8167)
Resolving deltas:  84% (6862/8167)
Resolving deltas:  85% (6989/8167)
Resolving deltas:  86% (7081/8167)
Resolving deltas:  87% (7124/8167)
Resolving deltas:  88% (7247/8167)
Resolving deltas:  89% (7284/8167)
Resolving deltas:  90% (7368/8167)
Resolving deltas:  91% (7507/8167)
Resolving deltas:  92% (7548/8167)
Resolving deltas:  93% (7669/8167)
Resolving deltas:  94% (7679/8167)
Resolving deltas:  95% (7762/8167)
Resolving deltas:  96% (7854/8167)
Resolving deltas:  97% (7924/8167)
Resolving deltas:  98% (8016/8167)
Resolving deltas:  99% (8103/8167)
Resolving deltas: 100% (8167/8167)
Resolving deltas: 100% (8167/8167), done.
,
,js脚本更新完成...
,
,/jd/config/crontab.list 文件不存在，请先定义你自己的crontab.list...
,
,检测到package.json有变化，运行 npm install...
,
,检测到本机安装了 yarn，使用 yarn 替代 npm...
,
,yarn install v1.22.5
,info No lockfile found.
,warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
,[1/4] Resolving packages...
,warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
,warning request > har-validator@5.1.5: this library is no longer supported
,[2/4] Fetching packages...
,[] 0/211[] 5/211[] 6/211[] 8/211[] 13/211[] 16/211[] 18/211[] 19/211[] 21/211[] 23/211[] 26/211[] 31/211[] 34/211[] 35/211[] 38/211[] 39/211[] 42/211[] 46/211[] 47/211[] 49/211[] 51/211[] 53/211[] 55/211[] 57/211[] 60/211[] 61/211[] 62/211[] 63/211[] 64/211[] 65/211[] 67/211[] 71/211[] 72/211[] 73/211[] 76/211[] 77/211[] 80/211[] 81/211[] 83/211[] 85/211[] 86/211[] 88/211[] 89/211[] 90/211[] 93/211[] 95/211[] 96/211[] 98/211[] 100/211[] 102/211[] 103/211[] 106/211[] 111/211[] 113/211[] 115/211[] 119/211[] 121/211[] 123/211[] 126/211[] 129/211[] 130/211[] 131/211[] 132/211[] 134/211[] 136/211[] 137/211[] 138/211[] 139/211[] 141/211[] 142/211[] 143/211[] 146/211[] 148/211[] 149/211[] 150/211[] 151/211[] 152/211[] 154/211[] 156/211[] 157/211[] 159/211[] 161/211[] 163/211[] 164/211[] 165/211[] 166/211[] 167/211[] 168/211[] 170/211[] 173/211[] 174/211[] 175/211[] 176/211[] 178/211[] 180/211[] 182/211info There appears to be trouble with your network connection. Retrying...
,[] 184/211[] 186/211[] 189/211[] 190/211[] 193/211[] 195/211[] 197/211[] 198/211[] 201/211[] 203/211[] 205/211[] 206/211[] 207/211[] 208/211[] 209/211[] 210/211[3/4] Linking dependencies...
,[] 211/211[] 0/216[] 0/3017[] 512/3017[] 943/3017[] 1407/3017[] 1917/3017[] 2385/3017[] 2938/3017[] 0/399[4/4] Building fresh packages...
,success Saved lockfile.
,Done in 37.27s.
,

**Comment by UMRQWQ** [comment]
好像启动成功了，但是面板访问不了  报500 Internal Privoxy Error

**Comment by UMRQWQ** [comment]
我把项目拉到服务器上用pm2运行  发现 虽然任务在做  但是  面板pm2启动不起来，一直失败

**Comment by dockere** [comment]
不清楚，没遇到过，如旁路由请添加docker run里添加--network host
