### ISSUE TITLE
️环球挑战赛报错

### ISSUE THREAD

**Issue by flhs0606** [dockere/jd-base#11]
❗️环球挑战赛, 错误!
TypeError: Cannot read property 'currDays' of undefined
    at /jd/scripts/jd_global.js:171:55
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️环球挑战赛, 错误!
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at /jd/scripts/jd_global.js:198:26
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️环球挑战赛, 错误!
TypeError: Cannot read property 'filter' of undefined
    at /jd/scripts/jd_global.js:153:48
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
接口降级
接口降级
接口降级
接口降级
接口降级
接口降级

**Comment by dockere** [comment]
> ❗️环球挑战赛, 错误!
> TypeError: Cannot read property 'currDays' of undefined
> at /jd/scripts/jd_global.js:171:55
> at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> ❗️环球挑战赛, 错误!
> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> at /jd/scripts/jd_global.js:198:26
> at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> ❗️环球挑战赛, 错误!
> TypeError: Cannot read property 'filter' of undefined
> at /jd/scripts/jd_global.js:153:48
> at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 接口降级
> 接口降级
> 接口降级
> 接口降级
> 接口降级
> 接口降级

脚本本身问题

**Comment by dockere** [comment]
> > ❗️环球挑战赛, 错误!
> > TypeError: Cannot read property 'currDays' of undefined
> > at /jd/scripts/jd_global.js:171:55
> > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > ❗️环球挑战赛, 错误!
> > TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> > at /jd/scripts/jd_global.js:198:26
> > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > ❗️环球挑战赛, 错误!
> > TypeError: Cannot read property 'filter' of undefined
> > at /jd/scripts/jd_global.js:153:48
> > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > 接口降级
> > 接口降级
> > 接口降级
> > 接口降级
> > 接口降级
> > 接口降级
> 
> 脚本本身问题

测试手动没问题；在定时设定后面加个now，不延迟试试
0 9,12,20,21 * * * bash jd jd_global now

**Comment by flhs0606** [comment]
> al no
谢谢，我试试

**Comment by flhs0606** [comment]
> > > ❗️环球挑战赛, 错误!
> > > TypeError: Cannot read property 'currDays' of undefined
> > > at /jd/scripts/jd_global.js:171:55
> > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > ❗️环球挑战赛, 错误!
> > > TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> > > at /jd/scripts/jd_global.js:198:26
> > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > ❗️环球挑战赛, 错误!
> > > TypeError: Cannot read property 'filter' of undefined
> > > at /jd/scripts/jd_global.js:153:48
> > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > 接口降级
> > > 接口降级
> > > 接口降级
> > > 接口降级
> > > 接口降级
> > > 接口降级
> > 
> > 
> > 脚本本身问题
> 
> 测试手动没问题；在定时设定后面加个now，不延迟试试
> 0 9,12,20,21 * * * bash jd jd_global now

手动执行才成功，自动的话加了now也不行

**Comment by dockere** [comment]
> > > > ❗️环球挑战赛, 错误!
> > > > TypeError: Cannot read property 'currDays' of undefined
> > > > at /jd/scripts/jd_global.js:171:55
> > > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > > ❗️环球挑战赛, 错误!
> > > > TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> > > > at /jd/scripts/jd_global.js:198:26
> > > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > > ❗️环球挑战赛, 错误!
> > > > TypeError: Cannot read property 'filter' of undefined
> > > > at /jd/scripts/jd_global.js:153:48
> > > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > > 接口降级
> > > > 接口降级
> > > > 接口降级
> > > > 接口降级
> > > > 接口降级
> > > > 接口降级
> > > 
> > > 
> > > 脚本本身问题
> > 
> > 
> > 测试手动没问题；在定时设定后面加个now，不延迟试试
> > 0 9,12,20,21 * * * bash jd jd_global now
> 
> 手动执行才成功，自动的话加了now也不行

测试是默认cron整点运行的锅；手动更改cron不整点运行

**Comment by flhs0606** [comment]
> > > > > ❗️环球挑战赛, 错误!
> > > > > TypeError: Cannot read property 'currDays' of undefined
> > > > > at /jd/scripts/jd_global.js:171:55
> > > > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > > > ❗️环球挑战赛, 错误!
> > > > > TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> > > > > at /jd/scripts/jd_global.js:198:26
> > > > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > > > ❗️环球挑战赛, 错误!
> > > > > TypeError: Cannot read property 'filter' of undefined
> > > > > at /jd/scripts/jd_global.js:153:48
> > > > > at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_global.js:492:4869)
> > > > > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > > > > 接口降级
> > > > > 接口降级
> > > > > 接口降级
> > > > > 接口降级
> > > > > 接口降级
> > > > > 接口降级
> > > > 
> > > > 
> > > > 脚本本身问题
> > > 
> > > 
> > > 测试手动没问题；在定时设定后面加个now，不延迟试试
> > > 0 9,12,20,21 * * * bash jd jd_global now
> > 
> > 
> > 手动执行才成功，自动的话加了now也不行
> 
> 测试是默认cron整点运行的锅；手动更改cron不整点运行

好的，我继续试试。另外刚刚测试手动bash jd jd_global_mh now也是失败的

**Comment by dockere** [comment]
> jd_global_mh

jd_global_mh结束了吧？

**Comment by flhs0606** [comment]
> > jd_global_mh
> 
> jd_global_mh结束了吧？

疏忽了！没注意不好意思哈
