### ISSUE TITLE
4/2日pull镜像后无法正常启动

### ISSUE THREAD

**Issue by duzhor** [dockere/jd-base#112]
群晖 `docker pull noobx/jd:gitee`，配置好启动后容器运行正常，无法访问5678端口。
进容器后发现未绑定5678端口， `pm2 list`  中 server 日志 `/root/.pm2/logs/server-error.log` 报npm依赖缺失错误。
[pm2 list](https://sm.ms/image/5XtPBJb2yquNIVm)
[server](https://sm.ms/image/GOD9N3v1A28FEUX)

在容器内执行 `npm install -g express express-session got` 后解决该问题。
重启容器后服务正常。

**Comment by caliban511** [comment]
我也遇到了，我这边是自动更新的，结果更新后完全没了动静，签到停了，所有任务都不执行了。

**Comment by UMRQWQ** [comment]
pm2启动不起来

**Comment by dockere** [comment]
目前的镜像是启动容器后安装lxk脚本的依赖，应该是部分地区网络启动容器后没有安装到依赖所导致的；之前是考虑镜像大小问题，lxk的依赖包和脚本没有集成在镜像里，最新镜像已经集成了lxk的所有依赖，如还有此问题，请更新镜像。。

**Comment by caliban511** [comment]
> 
> 
> 目前的镜像是启动容器后安装lxk脚本的依赖，应该是部分地区网络启动容器后没有安装到依赖所导致的；之前是考虑镜像大小问题，lxk的依赖包和脚本没有集成在镜像里，最新镜像已经集成了lxk的所有依赖，如更新镜像后还有此问题，请反馈。。

大佬辛苦了，这么晚了还在更新，非常感谢。
