### ISSUE TITLE
pm2启动server.js启动失败，面板无法进入

### ISSUE THREAD

**Issue by UMRQWQ** [dockere/jd-base#113]
![QQ截图20210403025207](https://user-images.githubusercontent.com/27806444/113445246-18c37f00-9428-11eb-971d-993bcb850da9.png)
这是一个全新的镜像docker中的pm2日志，启动不了

**Comment by dockere** [comment]
目前的镜像是启动容器后安装lxk脚本的依赖，应该是部分地区网络启动容器后没有安装到依赖所导致的；之前是考虑镜像大小问题，lxk的依赖包和脚本没有集成在镜像里，最新镜像已经集成了lxk的所有依赖，如更新镜像后还有此问题，请反馈。。

**Comment by UMRQWQ** [comment]
> 目前的镜像是启动容器后安装lxk脚本的依赖，应该是部分地区网络启动容器后没有安装到依赖所导致的；之前是考虑镜像大小问题，lxk的依赖包和脚本没有集成在镜像里，最新镜像已经集成了lxk的所有依赖，如更新镜像后还有此问题，请反馈。。

![QQ截图20210403160619](https://user-images.githubusercontent.com/27806444/113472533-958d4200-9496-11eb-8841-29c697766e8c.png)
我把6个目录全部映射出来 面板启动不了。。。我重新创建容器  只映射那两个目录就能正常访问

**Comment by UMRQWQ** [comment]
> 目前的镜像是启动容器后安装lxk脚本的依赖，应该是部分地区网络启动容器后没有安装到依赖所导致的；之前是考虑镜像大小问题，lxk的依赖包和脚本没有集成在镜像里，最新镜像已经集成了lxk的所有依赖，如更新镜像后还有此问题，请反馈。。

果然是映射目录的问题，我测试只能映射3个目录，映射第四个目录的话，pm2就会启动失败
