### ISSUE TITLE
自定义仓库更新失败 i-chenzhe

### ISSUE THREAD

**Issue by lfscqk67** [dockere/jd-base#116]
如题
![Screenshot_2021-04-04-22-42-58-189_com tencent mm](https://user-images.githubusercontent.com/37235589/113512449-4975f680-9597-11eb-81ad-232a81ee82f5.jpg)

**Comment by dockere** [comment]
？

**Comment by lfscqk67** [comment]
> ？

这是为啥呀大佬

**Comment by dockere** [comment]
就一个通知，我能看出啥。
