### ISSUE TITLE
不能扫码获取cookies？

### ISSUE THREAD

**Issue by leungzw** [dockere/jd-base#120]
没有看到UI是哪呢

**Comment by kalagxw** [comment]
看到 panel 里把扫码获取cookies相关代码删了。为啥呢

**Comment by nick814** [comment]
> 看到 panel 里把扫码获取cookies相关代码删了。为啥呢

增加使用难度  尽量减少tb xy卖的

**Comment by ekonoob** [comment]
楼上正解，门槛有点低了！
