### ISSUE TITLE
容器老是找不到端口怎么办，重新设置后端口一天就又要重新设置了

### ISSUE THREAD

**Issue by Woody-Wan** [dockere/jd-base#124]

**Comment by Woody-Wan** [comment]
这个情况还是运行了2个月第一次出现，很头疼

**Comment by Woody-Wan** [comment]
我按照大佬的5678端口再次安装了，隔了一会就不能从网页访问页面了。但是Portainer访问就是正常的

**Comment by dockere** [comment]
docker logs -f jd 看下

**Comment by Woody-Wan** [comment]
正在尝试通过重新安装改变端口，如果出现同类问题我会附上相应日志

**Comment by dockere** [comment]
-p 5678:5678 \ 也可以改成其他端口，如：
 ````
    -p 5679:5678 \
    -p 5677:5678 \
````

**Comment by Woody-Wan** [comment]
> -p 5678:5678 \ 也可以改成其他端口，如：
> 
> ```
>    -p 5679:5678 \
>    -p 5677:5678 \
> ```

好的，感谢指点
