### ISSUE TITLE
今日更新如何理解

### ISSUE THREAD

**Issue by qianxu2001** [dockere/jd-base#125]
今天更新说明我有些不太明白，是需要删除映射出来的 scripts 目录才能后续正常更新？我之前一直没映射这个目录出来，需要操作什么吗？

**Comment by dockere** [comment]
手动执行: docker exec -it jd bash git_pull
试下，能正常拉取就不用其他操作了，不能拉取就重新pull下镜像。

**Comment by qianxu2001** [comment]
那应该没什么问题了
<details>
<summary>日志</summary>
<pre><code>
root@debian:~# docker exec -it jd bash git_pull

--------------------------------------------------------------

系统时间：2021-04-24 20:39:01

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/dockere/jd-base

Fetching origin
HEAD is now at 06a187f update

shell脚本更新完成...

更新lxk0301脚本，原地址：https://gitee.com/lxk0301/jd_docker

Fetching origin
HEAD is now at 2444e082 fix

js脚本更新完成...

root@debian:~#
</code></pre>
</details>

**Comment by dockere** [comment]
嗯，能更新到jd_tcl.js就行了
