### ISSUE TITLE
MyHealth1="" 这个参数没用

### ISSUE THREAD

**Issue by nick814** [dockere/jd-base#127]
我在配置里加好MyHealth的互助了，但是看执行的日志没用，还是用的js里自带的互助码

**Comment by ekonoob** [comment]
查看下config.sh最后面的"互助码填法示例 "用法。

**Comment by nick814** [comment]
> 查看下config.sh最后面的"互助码填法示例 "用法。

哦对。写错了。谢谢

**Comment by ekonoob** [comment]
客气
