### ISSUE TITLE
领现金限时活动兑换京豆

### ISSUE THREAD

**Issue by xiaofsu** [dockere/jd-base#128]
![image](https://user-images.githubusercontent.com/46067472/116491690-0de7f700-a8cd-11eb-8c35-2236550264ee.png)
![image](https://user-images.githubusercontent.com/46067472/116491703-150f0500-a8cd-11eb-9553-07fe36448ed9.png)

希望可以可以添加一个选项来控制是否开启**兑换京豆**功能

![image](https://user-images.githubusercontent.com/46067472/116491801-4982c100-a8cd-11eb-98c9-e8332b480d3e.png)

lxk大佬的控制貌似是这个。

**Comment by ekomax** [comment]
昨天就加了哦；对比工具对比更新下

**Comment by dockere** [comment]
好，谢谢，昨天就更新了，不知道为何是更新到gitee去了，然后github强制推送覆盖了，现已更新

**Comment by xiaofsu** [comment]
OK，看到了多谢。
