### ISSUE TITLE
扫码获取cookies 希望再加上吧，帮亲戚朋友们挂的号，都来玩我怎么搞。我也没这么多浏览器可以帮他们

### ISSUE THREAD

**Issue by jasonpuff** [dockere/jd-base#130]

**Comment by dockere** [comment]
有空看看

**Comment by tom315187917** [comment]
> 有空看看

请问有安装方法吗？或者你把安装方法发到我邮箱（315187917@qq.com)，谢谢。

**Comment by cikichen** [comment]
同求扫码的，方便很多

**Comment by xiaofsu** [comment]
我也不太清楚当初扫码取消的初衷是什么。不过你说没有那么多浏览器可以搞这个问题可以解决。例如google或者edge浏览器，选项设置中都有 打开私有化窗口。登陆获取到信息之后，直接关掉私有化窗口，再新打开就恢复到无登录状态。原先的登录因为你没有退出，也是正常的。

**Comment by jasonpuff** [comment]
感谢提供解决思路，我也找了下相关的文章，准备写个pythons 试试


xiaofsu ***@***.***>于2021年5月2日 周日上午5:36写道：
