### ISSUE TITLE
来客有礼“发现”tab，点了N次，还是无法获取token

### ISSUE THREAD

**Issue by ryan016** [dockere/jd-base#132]
```
宠汪汪赛跑
【提示】来客有礼token失效，请重新获取
iOS用户微信搜索'来客有礼'小程序
点击底部的'发现'Tab
即可获取Token
```

其他人会不会也这样啊？今早才这样的。

**Comment by ekonoob** [comment]
这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧

**Comment by dockere** [comment]
这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧

**Comment by ryan016** [comment]
> 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧


> 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧

好几天了，都获取不了，你也是一样吗？？？

**Comment by dockere** [comment]
> > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> 
> > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> 
> 好几天了，都获取不了，你也是一样吗？？？

lxk脚本作者关了，docker用不了，自己手机自行获取token吧

**Comment by ryan016** [comment]
> > > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> > 
> > 
> > > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> > 
> > 
> > 好几天了，都获取不了，你也是一样吗？？？
> 
> lxk脚本作者关了，docker用不了，自己手机自行获取token吧
请问获取后填在哪里呢？谢谢！！

**Comment by ekonoob** [comment]
> > > > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> > > 
> > > 
> > > > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> > > 
> > > 
> > > 好几天了，都获取不了，你也是一样吗？？？
> > 
> > 
> > lxk脚本作者关了，docker用不了，自己手机自行获取token吧
> > 请问获取后填在哪里呢？或者说该如何使用呢？谢谢！！

添加作者的boxjs订阅

**Comment by ryan016** [comment]
> > > > > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> > > > 
> > > > 
> > > > > 这个token是lxk那边获取给docker用的，刚试了下确实会提示，明天看看吧
> > > > 
> > > > 
> > > > 好几天了，都获取不了，你也是一样吗？？？
> > > 
> > > 
> > > lxk脚本作者关了，docker用不了，自己手机自行获取token吧
> > > 请问获取后填在哪里呢？或者说该如何使用呢？谢谢！！
> 
> 添加作者的boxjs订阅

docker用户没有办法就是了？只能手机跑代码……
