### ISSUE TITLE
无法更新脚本（镜像已更新）

### ISSUE THREAD

**Issue by GokouRuriW** [dockere/jd-base#135]
“更新LXK大佬脚本

Fetching origin
Access deined: DeployKey not enabled
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at a1cbf3fb Merge branch 'master' of https://gitee.com/lxk0301/jd_scripts.git”

**Comment by ryan016** [comment]
都一样的。。。

**Comment by dockere** [comment]
由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新

**Comment by ryan016** [comment]
欧了，重新拉取后正常使用！



> 由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新

问个与此主题无关的问题，请问如何将宠汪汪抓取到的token用于docker的跑脚本上呢？谢谢！

**Comment by dockere** [comment]
> 欧了，重新拉取后正常使用！
> 
> > 由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新
> 
> 问个与此主题无关的问题，请问如何将宠汪汪抓取到的token用于docker的跑脚本上呢？谢谢！

不切实际，因为时效性很短
