### ISSUE TITLE
docker运行js脚本更新失败

### ISSUE THREAD

**Issue by Fookdies301** [dockere/jd-base#136]
========================1. 更新源代码========================

系统时间：crond[8]: crond (busybox 1.31.1) started, log level 8
2021-05-07 16:18:05

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

更新shell脚本，原地址：https://gitee.com/dockere/jd-base

Fetching origin
HEAD is now at 1379f0e no message

shell脚本更新完成...

Cloning into '/jd/scripts'...
Access deined: DeployKey not enabled
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by dockere** [comment]
由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新

**Comment by huairen945** [comment]
> 由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新

怎么重新拉取镜像更新?  我用docker-compose pull拉取不行呢

**Comment by huairen945** [comment]
> > 由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新
> 
> 怎么重新拉取镜像更新? 我用docker-compose pull拉取不行呢

命令用错了 没有compose  不好意思 打扰了

**Comment by huairen945** [comment]
> > > 由于jd_scripts仓库频繁更新失败,故作者关闭之前的ssh_key,换了一个新的key并且构建了新的镜像，请重新拉取新镜像更新
> > 
> > 
> > 怎么重新拉取镜像更新? 我用docker-compose pull拉取不行呢
> 
> 命令用错了 没有compose 不好意思 打扰了

拉取了最新镜像,还是提示Access deined: DeployKey not enabled
