### ISSUE TITLE
Cookie 达到12个以上，只执行12个

### ISSUE THREAD

**Issue by HUiTHEME** [dockere/jd-base#138]
我Cookie一共有17个，无论我是添加14个还是13个还是16个，都只运行12个，我也考虑是不是我ck里有乱码字符所以不执行，就添加14个纯数字的ck，也就是pt_pin=里的值有乱码的我先不添加，结果还是只执行12个Cookie，不知所措了。。。

**Comment by dockere** [comment]
没有做ck的限制，请问是哪个脚本？

**Comment by HUiTHEME** [comment]
https://registry.hub.docker.com/r/nevinee/jd/  好像是这个  v4的

**Comment by ekomax** [comment]
> https://registry.hub.docker.com/r/nevinee/jd/ 好像是这个 v4的

E大限制了12个CK

**Comment by HUiTHEME** [comment]
我网上找了一堆，有无解除限制的教程哈，谢谢了
&nbsp;


疯狂的大叔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月9日(星期天) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dockere/jd-base] Cookie 达到12个以上，只执行12个 (#138)





  
https://registry.hub.docker.com/r/nevinee/jd/ 好像是这个 v4的
  
E大限制了12个CK

**Comment by ekomax** [comment]
不了解哦

**Comment by dockere** [comment]
> https://registry.hub.docker.com/r/nevinee/jd/ 好像是这个 v4的

这个限制了12个CK，自己想办法吧！
