### ISSUE TITLE
今天git_pull之后似乎不太正常了

### ISSUE THREAD

**Issue by hewitt29** [dockere/jd-base#14]
提示npm install失败，然后脚本运行都报错了

ps: 我是armv7的设备

**Comment by dockere** [comment]
> 提示npm install失败，然后脚本运行都报错了
> 
> ps: 我是armv7的设备

重新构建了镜像，armv7没测试；重新pull下自行测试下吧

**Comment by hewitt29** [comment]
> > 提示npm install失败，然后脚本运行都报错了
> > ps: 我是armv7的设备
> 
> 重新构建了镜像，armv7没测试；重新pull下自行测试下吧

感谢大佬，试了一下基本运行正常
