### ISSUE TITLE
一直没有重新拉取新镜像，但是好像正常。是否不需要重新拉取镜像？

### ISSUE THREAD

**Issue by photonmang** [dockere/jd-base#143]
Fetching origin
HEAD is now at c2d8fbf update

shell脚本更新完成...

更新lxk0301脚本，原地址：https://gitee.com/lxk0301/jd_docker

Fetching origin
HEAD is now at cef91e39 需要手动进入一下活动页面。不然即使是开启了这个活动。跑脚本也提示未开启活动。 收益过低，可注释不用。

js脚本更新完成...

**Comment by dockere** [comment]
你可能装了自动更新镜像的。能正常拉取lxk作者的脚本就行了
