### ISSUE TITLE
自定义脚本更新的问题。

### ISSUE THREAD

**Issue by photonmang** [dockere/jd-base#145]
我看V4的面板里可以直接自定义更新脚本链接下的所有脚本。而diy里我这边配置的，需要一个个加脚本名称。请问下作者有没有可以直接适配的自定义脚本，如下面这种脚本的匹配方式？
 OwnRepoUrl1="https://gitee.com/abc/jdtsa.git"
 OwnRepoUrl2="https://github.com/nedcd/jxddfsa.git"
 OwnRepoUrl3="git@github.com:eject/poex.git"
 
 OwnRepoBranch1=""         # 代表第1个仓库 https://gitee.com/abc/jdtsa.git 使用 "默认" 分支
 OwnRepoBranch2="main"     # 代表第2个仓库 https://github.com/nedcd/jxddfsa.git 使用 "main" 分支
 OwnRepoBranch3="master"   # 代表第3个仓库 git@github.com:eject/poex.git 使用 "master" 分支
 
 OwnRepoPath1=""                   # 代表第1个仓库https://gitee.com/abc/jdtsa.git，你想使用的脚本就在仓库根目录下。
 OwnRepoPath2="scripts/jd normal"  # 代表第2个仓库https://github.com/nedcd/jxddfsa.git，你想使用的脚本在仓库的 scripts/jd 和 normal文件夹下，必须输入相对路径
 OwnRepoPath3="'' cron"            # 代表第3个仓库git@github.com:eject/poex.git，你想使用的脚本在仓库的 根目录 和 cron 文件夹下，必须输入相对路径

**Comment by ekomax** [comment]
这个用V4就行了呀

**Comment by dockere** [comment]
这个用V4就行了呀！
