### ISSUE TITLE
shell脚本更新失败

### ISSUE THREAD

**Issue by q9331** [dockere/jd-base#147]
系统时间：2021-05-22 10:18:57

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/dockere/jd-base

Fetching origin
fatal: unable to access 'https://gitee.com/dockere/jd-base/': Failed to connect to gitee.com port 443: Connection refused
error: Could not fetch origin
HEAD is now at efbec45 update

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

更新lxk0301脚本，原地址：https://gitee.com/lxk0301/jd_docker

Fetching origin
ssh: connect to host gitee.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at 2ca7ab40 增加循环次数判断，防止未判断的情况死循环

js脚本更新失败，请检查原因或再次运行git_pull.sh...

是什么原因导致这个问题的？

**Comment by dockere** [comment]
网络原因
