### ISSUE TITLE
关于新活动的助力码

### ISSUE THREAD

**Issue by ryan016** [dockere/jd-base#148]
config.sh.sample里新增了城城领现金互和手机狂欢城互助
但不论我是git_pull还是重新拉取镜像
控制面板里的config都没有这两块的内容
查看 config.sh.sample也是没有这两部分内容
手动复制粘贴也没有起到彼此之间助力的作用
提示"您提供了0个账号的城城领现金助力码"
请问该如何操作？
谢谢！！！

**Comment by dockere** [comment]
配置文件拉下去最下面有示例

**Comment by ryan016** [comment]
问题已解决，重新git_pull后有了
11点20分的时候git_pull无效果
谢谢！！

**Comment by dockere** [comment]
行
