### ISSUE TITLE
N1上，F大53+o固件，出错了？

### ISSUE THREAD

**Issue by shenzt68** [dockere/jd-base#16]
--------------------------------------------------------------
,
,系统时间：2021-02-20 21:35:23
,
,SHELL脚本目录：/jd
,
,JS脚本目录：/jd/scripts
,
,--------------------------------------------------------------
,
,更新shell脚本，原地址：https://github.com/dockere/jd-base
,
,Fetching origin
,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
,error: Could not fetch origin
,HEAD is now at ba1fb90 update
,
,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
,
,js脚本更新完成...
,
,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
,/usr/local/bin/git_pull: line 184: cd: /jd/scripts: No such file or directory
,cat: package.json: No such file or directory
,运行 npm install...
,
,检测到本机安装了 yarn，使用 yarn 替代 npm...
,
,yarn install v1.22.5
,[1/4] Resolving packages...
,success Already up-to-date.
,Done in 0.49s.
,/usr/local/bin/git_pull: line 224: [: -eq: unary operator expected
,
,========================2. 检测配置文件========================
,
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,
,成功添加定时任务...
,
,========================3. 启动挂机程序========================
,
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,[PM2] PM2 Successfully daemonized
,[PM2] Flushing /root/.pm2/pm2.log
,[PM2] Logs flushed
,Use --update-env to update environment variables
,
,========================1. 更新源代码========================
,
,crond[7]: crond (busybox 1.31.1) started, log level 8
,
,--------------------------------------------------------------
,
,系统时间：2021-02-20 21:35:32
,
,SHELL脚本目录：/jd
,
,JS脚本目录：/jd/scripts
,
,--------------------------------------------------------------
,
,更新shell脚本，原地址：https://github.com/dockere/jd-base
,
,Fetching origin
,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
,error: Could not fetch origin
,HEAD is now at ba1fb90 update
,
,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
,
,js脚本更新完成...
,
,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
,/usr/local/bin/git_pull: line 184: cd: /jd/scripts: No such file or directory
,cat: package.json: No such file or directory
,运行 npm install...
,
,检测到本机安装了 yarn，使用 yarn 替代 npm...
,
,yarn install v1.22.5
,[1/4] Resolving packages...
,success Already up-to-date.
,Done in 0.49s.
,/usr/local/bin/git_pull: line 224: [: -eq: unary operator expected
,
,========================2. 检测配置文件========================
,
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,
,成功添加定时任务...
,
,========================3. 启动挂机程序========================
,
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,[PM2] PM2 Successfully daemonized
,[PM2] Flushing /root/.pm2/pm2.log
,[PM2] Logs flushed
,

**Comment by dockere** [comment]
> ,
> ,系统时间：2021-02-20 21:35:23
> ,
> ,SHELL脚本目录：/jd
> ,
> ,JS脚本目录：/jd/scripts
> ,
> ,--------------------------------------------------------------
> ,
> ,更新shell脚本，原地址：https://github.com/dockere/jd-base
> ,
> ,Fetching origin
> ,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
> ,error: Could not fetch origin
> ,HEAD is now at [ba1fb90](https://github.com/dockere/jd-base/commit/ba1fb902c532d850c5874a92d290125f7e05dece) update
> ,
> ,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> ,
> ,js脚本更新完成...
> ,
> ,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
> ,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
> ,/usr/local/bin/git_pull: line 184: cd: /jd/scripts: No such file or directory
> ,cat: package.json: No such file or directory
> ,运行 npm install...
> ,
> ,检测到本机安装了 yarn，使用 yarn 替代 npm...
> ,
> ,yarn install v1.22.5
> ,[1/4] Resolving packages...
> ,success Already up-to-date.
> ,Done in 0.49s.
> ,/usr/local/bin/git_pull: line 224: [: -eq: unary operator expected
> ,
> ,========================2. 检测配置文件========================
> ,
> ,检测到config配置目录下存在crontab.list，自动导入定时任务...
> ,
> ,成功添加定时任务...
> ,
> ,========================3. 启动挂机程序========================
> ,
> ,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
> ,[PM2] PM2 Successfully daemonized
> ,[PM2] Flushing /root/.pm2/pm2.log
> ,[PM2] Logs flushed
> ,Use --update-env to update environment variables
> ,
> ,========================1. 更新源代码========================
> ,
> ,crond[7]: crond (busybox 1.31.1) started, log level 8
> ,
> ,--------------------------------------------------------------
> ,
> ,系统时间：2021-02-20 21:35:32
> ,
> ,SHELL脚本目录：/jd
> ,
> ,JS脚本目录：/jd/scripts
> ,
> ,--------------------------------------------------------------
> ,
> ,更新shell脚本，原地址：https://github.com/dockere/jd-base
> ,
> ,Fetching origin
> ,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
> ,error: Could not fetch origin
> ,HEAD is now at [ba1fb90](https://github.com/dockere/jd-base/commit/ba1fb902c532d850c5874a92d290125f7e05dece) update
> ,
> ,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> ,
> ,js脚本更新完成...
> ,
> ,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
> ,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
> ,/usr/local/bin/git_pull: line 184: cd: /jd/scripts: No such file or directory
> ,cat: package.json: No such file or directory
> ,运行 npm install...
> ,
> ,检测到本机安装了 yarn，使用 yarn 替代 npm...
> ,
> ,yarn install v1.22.5
> ,[1/4] Resolving packages...
> ,success Already up-to-date.
> ,Done in 0.49s.
> ,/usr/local/bin/git_pull: line 224: [: -eq: unary operator expected
> ,
> ,========================2. 检测配置文件========================
> ,
> ,检测到config配置目录下存在crontab.list，自动导入定时任务...
> ,
> ,成功添加定时任务...
> ,
> ,========================3. 启动挂机程序========================
> ,
> ,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
> ,[PM2] PM2 Successfully daemonized
> ,[PM2] Flushing /root/.pm2/pm2.log
> ,[PM2] Logs flushed
> ,

lxk大佬库被封了。暂时拉取不到JS
