### ISSUE TITLE
大佬能不能备份一个脚本仓库

### ISSUE THREAD

**Issue by ChangWeiCat** [dockere/jd-base#17]
这样L大那里出状况了，不影响安装和更新

**Comment by dockere** [comment]
先看看吧，暂时不加，lxk库目前还在商讨对策中。

**Comment by ChangWeiCat** [comment]
> 先看看吧，暂时不加，lxk库目前还在商讨对策中。

明确是raw的锅了，那就与docker关系不大。
你这个镜像有个自己的仓库，安装和更新就不会受上游限制，现在私库卡更新，diy.sh就不更新了，也新装不了。
镜像有配套仓库的话还可以添加一些非L大的零散脚本
我觉得您可以考虑一下

**Comment by phpnbw** [comment]
强烈要求弄个TG群，我感觉这个项目迟早也要被封。。

**Comment by tianya908** [comment]
强烈要求弄个TG群
