### ISSUE TITLE
大佬，更新了！

### ISSUE THREAD

**Issue by qq34347476** [dockere/jd-base#18]
好想对策出来了～大佬更新下啊

**Comment by qq34347476** [comment]
![image](https://user-images.githubusercontent.com/49470702/108619440-db9ac300-745f-11eb-90db-00105df2f0e0.png)
这？

**Comment by dockere** [comment]
> 好想对策出来了～大佬更新下啊

已经更新了呀，删除原来的镜像，重新拉取就好了。

**Comment by qq34347476** [comment]
直接 docker run -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower

么？

**Comment by dockere** [comment]
> 直接 docker run -d
> --name watchtower
> -v /var/run/docker.sock:/var/run/docker.sock
> containrrr/watchtower
> 
> 么？

直接删除重新拉取吧。。

**Comment by qq34347476** [comment]
镜像还是 noobx/jd:gitee 吗？
rmi 删掉，再下个这个吗？

**Comment by fly818** [comment]
更新到3点的那个镜像还是不可以拉取脚本

**Comment by dockere** [comment]
> 镜像还是 noobx/jd:gitee 吗？
> rmi 删掉，再下个这个吗？
嗯，删除容器与镜像，然后重新Pull,也可以试下下面的命令：
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once jd
```
试下

**Comment by dockere** [comment]
> 更新到3点的那个镜像还是不可以拉取脚本

都可以了，自己研究下吧

**Comment by toyfun** [comment]
> > 镜像还是 noobx/jd:gitee 吗？
> > rmi 删掉，再下个这个吗？
> 
> 嗯，删除容器与镜像，然后重新Pull,也可以试下下面的命令：
> 
> ```
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once jd
> ```
> 
> 试下


> > 镜像还是 noobx/jd:gitee 吗？
> > rmi 删掉，再下个这个吗？
> 
> 嗯，删除容器与镜像，然后重新Pull,也可以试下下面的命令：
> 
> ```
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once jd
> ```
> 
> 试下

谢谢大佬，直接复制搞定。感谢
