### ISSUE TITLE
大佬最新的镜像更新提示这个

### ISSUE THREAD

**Issue by 2375399351** [dockere/jd-base#19]
![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
是不是得开飞机啊？

**Comment by dockere** [comment]
> ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> 是不是得开飞机啊？

???不懂。

**Comment by 2375399351** [comment]
> > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > 是不是得开飞机啊？
> 
> ???不懂。

我也不懂啊……更新了下镜像启动就这样了……

**Comment by dockere** [comment]
> > > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > > 是不是得开飞机啊？
> > 
> > 
> > ???不懂。
> 
> 我也不懂啊……更新了下镜像启动就这样了……

有啥问题？

**Comment by 2375399351** [comment]
> > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > 是不是得开飞机啊？
> 
> ???不懂。



> > > > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > > > 是不是得开飞机啊？
> > > 
> > > 
> > > ???不懂。
> > 
> > 
> > 我也不懂啊……更新了下镜像启动就这样了……
> 
> 有啥问题？

启动不了，信息一直卡在最下面这里，我更新的是gitee那个

**Comment by 2375399351** [comment]
> > > > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > > > 是不是得开飞机啊？
> > > 
> > > 
> > > ???不懂。
> > 
> > 
> > 我也不懂啊……更新了下镜像启动就这样了……
> 
> 有啥问题？

![84A68780-0D68-497F-82E4-1B3F0A62C25F](https://user-images.githubusercontent.com/34334506/108621843-173d8900-7470-11eb-8ea7-286cde4ca774.png)
这是在更新脚本吗？

**Comment by dockere** [comment]
> > > > > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > > > > 是不是得开飞机啊？
> > > > 
> > > > 
> > > > ???不懂。
> > > 
> > > 
> > > 我也不懂啊……更新了下镜像启动就这样了……
> > 
> > 
> > 有啥问题？
> 
> ![84A68780-0D68-497F-82E4-1B3F0A62C25F](https://user-images.githubusercontent.com/34334506/108621843-173d8900-7470-11eb-8ea7-286cde4ca774.png)
> 这是在更新脚本吗？

这是进程，已经在跑脚本了，你进WEB面板看下就知道了。

**Comment by 2375399351** [comment]
> > > > > > ![2377E115-146C-40D4-ADB5-9DB7322CFD58](https://user-images.githubusercontent.com/34334506/108621739-66cf8500-746f-11eb-8167-0f029b0b6d18.png)
> > > > > > 是不是得开飞机啊？
> > > > > 
> > > > > 
> > > > > ???不懂。
> > > > 
> > > > 
> > > > 我也不懂啊……更新了下镜像启动就这样了……
> > > 
> > > 
> > > 有啥问题？
> > 
> > 
> > ![84A68780-0D68-497F-82E4-1B3F0A62C25F](https://user-images.githubusercontent.com/34334506/108621843-173d8900-7470-11eb-8ea7-286cde4ca774.png)
> > 这是在更新脚本吗？
> 
> 这是进程，已经在跑脚本了，你进WEB面板看下就知道了。

web进不去，好像没启动web面板的进程

**Comment by dockere** [comment]
重启下容器看看。

**Comment by 2375399351** [comment]
> 重启下容器看看。

我手动启动了web界面进程就正常了，是不是更新了没设置自动启动界面脚本？

**Comment by dockere** [comment]
> > 重启下容器看看。
> 
> 我手动启动了web界面进程就正常了，是不是更新了没设置自动启动界面脚本？

有的，重新安装静等1-2分钟就启动了。

**Comment by 2375399351** [comment]
> > > 重启下容器看看。
> > 
> > 
> > 我手动启动了web界面进程就正常了，是不是更新了没设置自动启动界面脚本？
> 
> 有的，重新安装静等1-2分钟就启动了。

试了下不行……
![D430A221-C3BF-4AA2-8C96-1FE23D2893F7](https://user-images.githubusercontent.com/34334506/108622113-997a7d00-7471-11eb-8b13-5798b433be7c.png)

**Comment by dockere** [comment]
执行docker exec -it jd pm2 monit 进入pm2查看server进程

**Comment by 2375399351** [comment]
> docker exec -it jd pm2 monit



> 执行docker exec -it jd pm2 monit 进入pm2查看server进程

可以了，这玩意莫名其妙啊……

**Comment by dockere** [comment]
> > docker exec -it jd pm2 monit
> 
> > 执行docker exec -it jd pm2 monit 进入pm2查看server进程
> 
> 可以了，这玩意莫名其妙啊……

因素很多吧，大部分的人还是正常的。

**Comment by 2375399351** [comment]
> > > docker exec -it jd pm2 monit
> > 
> > 
> > > 执行docker exec -it jd pm2 monit 进入pm2查看server进程
> > 
> > 
> > 可以了，这玩意莫名其妙啊……
> 
> 因素很多吧，大部分的人还是正常的。

恩，谢谢了大佬

**Comment by hysbeta** [comment]
遇到相同的问题 无法pull lxk的库 启动后一直卡住
把docker image删掉后 重新拉取image问题解决

**Comment by shange1993** [comment]
@dockere 我也老是这样，我开了代理了，白名单模式，这是怎么回事呢！
![QQ截图20210221221327](https://user-images.githubusercontent.com/46110324/108627823-79a78100-7492-11eb-9e71-30e8df647e10.png)

**Comment by dockere** [comment]
> @dockere 我也老是这样，我开了代理了，白名单模式，这是怎么回事呢！
> ![QQ截图20210221221327](https://user-images.githubusercontent.com/46110324/108627823-79a78100-7492-11eb-9e71-30e8df647e10.png)

你看楼上吧，明显你的旧镜像没有删除导致的。

**Comment by shange1993** [comment]
> > @dockere 我也老是这样，我开了代理了，白名单模式，这是怎么回事呢！
> > ![QQ截图20210221221327](https://user-images.githubusercontent.com/46110324/108627823-79a78100-7492-11eb-9e71-30e8df647e10.png)
> 
> 你看楼上吧，明显你的旧镜像没有删除导致的。

啊，我明明是把容器和镜像都删除了后，然后才下载安装的，对了，我用了阿里云加速，是不是你包没上传到阿里云呢

**Comment by dockere** [comment]
> > > @dockere 我也老是这样，我开了代理了，白名单模式，这是怎么回事呢！
> > > ![QQ截图20210221221327](https://user-images.githubusercontent.com/46110324/108627823-79a78100-7492-11eb-9e71-30e8df647e10.png)
> > 
> > 
> > 你看楼上吧，明显你的旧镜像没有删除导致的。
> 
> 啊，我明明是把容器和镜像都删除了后，然后才下载安装的，对了，我用了阿里云加速，是不是你包没上传到阿里云呢

不清楚，我push的是dockerhub官方上的。

**Comment by shange1993** [comment]
@dockere 刚把阿里云加速删除了，重新删除容器和镜像，然后下载后重新部署，还是这样，新下载下来的是218M应该没有错啊
![QQ截图20210221223206](https://user-images.githubusercontent.com/46110324/108628296-13702d80-7495-11eb-8dab-c97c3f823751.png)

**Comment by dockere** [comment]
> @dockere 刚把阿里云加速删除了，重新删除容器和镜像，然后下载后重新部署，还是这样，新下载下来的是218M应该没有错啊
> ![QQ截图20210221223206](https://user-images.githubusercontent.com/46110324/108628296-13702d80-7495-11eb-8dab-c97c3f823751.png)

新镜像已经内置秘钥了；问下你这个设备的相关人员吧。

**Comment by shange1993** [comment]
> > @dockere 刚把阿里云加速删除了，重新删除容器和镜像，然后下载后重新部署，还是这样，新下载下来的是218M应该没有错啊
> > ![QQ截图20210221223206](https://user-images.githubusercontent.com/46110324/108628296-13702d80-7495-11eb-8dab-c97c3f823751.png)
> 
> 新镜像已经内置秘钥了；问下你这个设备的相关人员吧。
啊，这个不是大佬你的镜像吗？

**Comment by 2375399351** [comment]
> > > @dockere 刚把阿里云加速删除了，重新删除容器和镜像，然后下载后重新部署，还是这样，新下载下来的是218M应该没有错啊
> > > ![QQ截图20210221223206](https://user-images.githubusercontent.com/46110324/108628296-13702d80-7495-11eb-8dab-c97c3f823751.png)
> > 
> > 
> > 新镜像已经内置秘钥了；问下你这个设备的相关人员吧。
> > 啊，这个不是大佬你的镜像吗？

* * * * * node /jd/panel/server.js
这个每分钟自动运行一次web界面的启动脚本

**Comment by avsba001** [comment]
> > > @dockere 我也老是这样，我开了代理了，白名单模式，这是怎么回事呢！
> > > ![QQ截图20210221221327](https://user-images.githubusercontent.com/46110324/108627823-79a78100-7492-11eb-9e71-30e8df647e10.png)
> > 
> > 
> > 你看楼上吧，明显你的旧镜像没有删除导致的。
> 
> 啊，我明明是把容器和镜像都删除了后，然后才下载安装的，对了，我用了阿里云加速，是不是你包没上传到阿里云呢

不要用国内加速源，同步成迷，1周不同步很正常，阿里源是阿里主动去dockerhub拉取,不是作者上传

**Comment by 2375399351** [comment]
> > > > @dockere 我也老是这样，我开了代理了，白名单模式，这是怎么回事呢！
> > > > ![QQ截图20210221221327](https://user-images.githubusercontent.com/46110324/108627823-79a78100-7492-11eb-9e71-30e8df647e10.png)
> > > 
> > > 
> > > 你看楼上吧，明显你的旧镜像没有删除导致的。
> > 
> > 
> > 啊，我明明是把容器和镜像都删除了后，然后才下载安装的，对了，我用了阿里云加速，是不是你包没上传到阿里云呢
> 
> 不要用国内加速源，同步成迷，1周不同步很正常，阿里源是阿里主动去dockerhub拉取,不是作者上传

我没用加速源，也这样。解决方法好像是删除scripts文件夹，让git_pull重新拉脚本
