### ISSUE TITLE
cookie更新失效

### ISSUE THREAD

**Issue by Mr-zhaohy** [dockere/jd-base#20]
昨天两个账号都提示过期，通过5678扫码获取并保存config.sh依旧提示失效...

**Comment by dockere** [comment]
自己正常；可能你号原因

**Comment by Mr-zhaohy** [comment]
> 自己正常；可能你号原因

我替换成其他账号或删除这两个账号的cookie，执行脚本依旧提示这两个账号过期

**Comment by Mr-zhaohy** [comment]
已找到问题，麻烦作者关闭，非常感谢🙏

**Comment by phpnbw** [comment]
是什么原因，我也遇到这个问题了

**Comment by Mr-zhaohy** [comment]
> 是什么原因，我也遇到这个问题了

我把config复制了两遍。。。 
上半部分改了，下半部分还是旧的

**Comment by dockere** [comment]
> > 是什么原因，我也遇到这个问题了
> 
> 我把config复制了两遍。。。
> 上半部分改了，下半部分还是旧的

不用复制吧，对比工具挺好用的啊！有差异的内容中间会有个箭头；点一下就过去了。
