### ISSUE TITLE
【已解决】大佬，用的最新镜像，容器安装时就报错。机器是阿里云-山东青岛

### ISSUE THREAD

**Issue by ChangWeiCat** [dockere/jd-base#22]
![image](https://user-images.githubusercontent.com/62734951/108625939-8d4dea00-7488-11eb-99c0-efadebddc337.png)

**Comment by dockere** [comment]
可能网络原因，容器里加入gitee 的hosts看看

**Comment by ChangWeiCat** [comment]
> 可能网络原因，容器里加入gitee 的hosts看看

不会加，大佬指导下
--add-host然后怎么写啊

**Comment by dockere** [comment]
> > 可能网络原因，容器里加入gitee 的hosts看看
> 
> 不会加，大佬指导下
> --add-host然后怎么写啊
爬下资料看看

**Comment by ChangWeiCat** [comment]
> > > 可能网络原因，容器里加入gitee 的hosts看看
> > 
> > 
> > 不会加，大佬指导下
> > --add-host然后怎么写啊
> > 爬下资料看看

谢谢大佬，今天重装直接就好了，大概是昨天网络的问题。
自己也学会了加key 收获满满
