### ISSUE TITLE
大佬啊，更新后一直报错怎么办？

### ISSUE THREAD

**Issue by shenzt68** [dockere/jd-base#23]
cat: package.json: No such file or directory
,/usr/local/bin/git_pull: line 220: [: -eq: unary operator expected
,
,========================2. 检测配置文件========================
,
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,
,成功添加定时任务...
,
,========================3. 启动挂机程序========================
,
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,[PM2] PM2 Successfully daemonized
,[PM2] Flushing /root/.pm2/pm2.log
,[PM2] Logs flushed
,Use --update-env to update environment variables
,
,========================1. 更新源代码========================
,
,crond[7]: crond (busybox 1.31.1) started, log level 8
,
,--------------------------------------------------------------
,
,系统时间：2021-02-21 21:00:09
,
,SHELL脚本目录：/jd
,
,JS脚本目录：/jd/scripts
,
,--------------------------------------------------------------
,
,更新shell脚本，原地址：https://github.com/dockere/jd-base
,
,Fetching origin
,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
,error: Could not fetch origin
,HEAD is now at dab9490 Update Dockerfile
,
,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
,
,js脚本更新完成...
,
,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
,cat: package.json: No such file or directory
,/usr/local/bin/git_pull: line 220: [: -eq: unary operator expected
,
,========================2. 检测配置文件========================
,
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,
,成功添加定时任务...
,
,========================3. 启动挂机程序========================
,
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,[PM2] PM2 Successfully daemonized
,[PM2] Flushing /root/.pm2/pm2.log
,[PM2] Logs flushed
,Use --update-env to update environment variables
,
,========================1. 更新源代码========================
,
,crond[7]: crond (busybox 1.31.1) started, log level 8
,
,--------------------------------------------------------------
,
,系统时间：2021-02-21 21:00:16
,
,SHELL脚本目录：/jd
,
,JS脚本目录：/jd/scripts
,
,--------------------------------------------------------------
,
,更新shell脚本，原地址：https://github.com/dockere/jd-base
,
,Fetching origin
,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
,error: Could not fetch origin
,HEAD is now at dab9490 Update Dockerfile
,
,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
,
,js脚本更新完成...
,
,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
,cat: package.json: No such file or directory
,/usr/local/bin/git_pull: line 220: [: -eq: unary operator expected
,
,========================2. 检测配置文件========================
,
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,
,成功添加定时任务...
,
,========================3. 启动挂机程序========================
,
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,

**Comment by dockere** [comment]
> cat: package.json: No such file or directory
> ,/usr/local/bin/git_pull: line 220: [: -eq: unary operator expected
> ,
> ,========================2. 检测配置文件========================
> ,
> ,检测到config配置目录下存在crontab.list，自动导入定时任务...
> ,
> ,成功添加定时任务...
> ,
> ,========================3. 启动挂机程序========================
> ,
> ,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
> ,[PM2] PM2 Successfully daemonized
> ,[PM2] Flushing /root/.pm2/pm2.log
> ,[PM2] Logs flushed
> ,Use --update-env to update environment variables
> ,
> ,========================1. 更新源代码========================
> ,
> ,crond[7]: crond (busybox 1.31.1) started, log level 8
> ,
> ,--------------------------------------------------------------
> ,
> ,系统时间：2021-02-21 21:00:09
> ,
> ,SHELL脚本目录：/jd
> ,
> ,JS脚本目录：/jd/scripts
> ,
> ,--------------------------------------------------------------
> ,
> ,更新shell脚本，原地址：https://github.com/dockere/jd-base
> ,
> ,Fetching origin
> ,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
> ,error: Could not fetch origin
> ,HEAD is now at [dab9490](https://github.com/dockere/jd-base/commit/dab949071ac3116b2e9f8ea3c5fefded495bb520) Update Dockerfile
> ,
> ,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> ,
> ,js脚本更新完成...
> ,
> ,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
> ,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
> ,cat: package.json: No such file or directory
> ,/usr/local/bin/git_pull: line 220: [: -eq: unary operator expected
> ,
> ,========================2. 检测配置文件========================
> ,
> ,检测到config配置目录下存在crontab.list，自动导入定时任务...
> ,
> ,成功添加定时任务...
> ,
> ,========================3. 启动挂机程序========================
> ,
> ,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
> ,[PM2] PM2 Successfully daemonized
> ,[PM2] Flushing /root/.pm2/pm2.log
> ,[PM2] Logs flushed
> ,Use --update-env to update environment variables
> ,
> ,========================1. 更新源代码========================
> ,
> ,crond[7]: crond (busybox 1.31.1) started, log level 8
> ,
> ,--------------------------------------------------------------
> ,
> ,系统时间：2021-02-21 21:00:16
> ,
> ,SHELL脚本目录：/jd
> ,
> ,JS脚本目录：/jd/scripts
> ,
> ,--------------------------------------------------------------
> ,
> ,更新shell脚本，原地址：https://github.com/dockere/jd-base
> ,
> ,Fetching origin
> ,fatal: unable to access 'https://github.com/dockere/jd-base/': Failed to connect to github.com port 443: Connection refused
> ,error: Could not fetch origin
> ,HEAD is now at [dab9490](https://github.com/dockere/jd-base/commit/dab949071ac3116b2e9f8ea3c5fefded495bb520) Update Dockerfile
> ,
> ,shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> ,
> ,js脚本更新完成...
> ,
> ,Can't open /jd/scripts/jd_joy_run.js: No such file or directory.
> ,cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
> ,cat: package.json: No such file or directory
> ,/usr/local/bin/git_pull: line 220: [: -eq: unary operator expected
> ,
> ,========================2. 检测配置文件========================
> ,
> ,检测到config配置目录下存在crontab.list，自动导入定时任务...
> ,
> ,成功添加定时任务...
> ,
> ,========================3. 启动挂机程序========================
> ,
> ,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
> ,

电信的吧，刚刚我也炸了，网络原因。github访问不了。

**Comment by shenzt68** [comment]
我是移动的

**Comment by dockere** [comment]
晚点再看看吧。确定是网络原因

**Comment by shenzt68** [comment]
5678web面板都进不去
