### ISSUE TITLE
大佬，我看到脚本已经更新了jd_try,但是你的pull不到这个？

### ISSUE THREAD

**Issue by justincnn** [dockere/jd-base#24]
请问何时可以更新脚本库，谢谢啊

**Comment by dockere** [comment]
> 请问何时可以更新脚本库，谢谢啊

有截图最好了；我看下什么原因吧，刚刚是github都炸了

**Comment by justincnn** [comment]
[jd_try.js.zip](https://github.com/dockere/jd-base/files/6017849/jd_try.js.zip)
就是这个脚本，我下下来了，麻烦看下

**Comment by dockere** [comment]
> [jd_try.js.zip](https://github.com/dockere/jd-base/files/6017849/jd_try.js.zip)
> 就是这个脚本，我下下来了，麻烦看下

有的，脚本不是在我库里，是lxk库里，手动执行：docker exec -it jd bash git_pull重新拉取脚本

**Comment by justincnn** [comment]
pull不到，好几遍都是一样的结局


![F97551C5-AB73-48AF-9E96-EE5733898C0D](https://user-images.githubusercontent.com/37951994/108628609-ef155080-7496-11eb-92bb-99380d23a563.png)

![DF9E18CC-41AD-48CE-A593-981F75E3250F](https://user-images.githubusercontent.com/37951994/108628613-f50b3180-7496-11eb-9779-8042461e72e2.png)，

**Comment by dockere** [comment]
保价不是jd_price.js吗？

**Comment by dockere** [comment]
你这都是正常的，docker exec -it jd bash jd jd_price now 就好了

**Comment by justincnn** [comment]
> 你这都是正常的，docker exec -it jd bash jd jd_price now 就好了

保价是正常的，但是没有京东试用，大佬要不再看看？

**Comment by Storm4542** [comment]
> > 你这都是正常的，docker exec -it jd bash jd jd_price now 就好了
> 
> 保价是正常的，但是没有京东试用，大佬要不再看看？

你这个不是lxk的脚本，不会在这里更新的，你可以手动加入运行

**Comment by dockere** [comment]
> > 你这都是正常的，docker exec -it jd bash jd jd_price now 就好了
> 
> 保价是正常的，但是没有京东试用，大佬要不再看看？

你先阅读confit.sh再看看吧
