### ISSUE TITLE
shell更新报错，及lxk脚本是否有可行的拉取方式？

### ISSUE THREAD

**Issue by encoo** [dockere/jd-base#28]
```

--------------------------------------------------------------

系统时间：2021-02-22 13:11:46

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://github.com/dockere/jd-base

Fetching origin
fatal: unable to access 'https://github.com/dockere/jd-base/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443
error: Could not fetch origin
HEAD is now at e29d603 Update Dockerfile

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

js脚本更新完成...

检测到package.json有变化，运行 npm install...

audited 207 packages in 6.022s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


/usr/local/bin/git_pull: line 217: [: -eq: unary operator expected



```

```
--------------------------------------------------------------

Fetching origin
Username for 'https://gitee.com':
Password for 'https://gitee.com':
remote: Unauthorized
fatal: Authentication failed for 'https://gitee.com/lxk0301/jd_scripts/'
error: Could not fetch origin
HEAD is now at 978ef05 jd_price.js

js脚本更新失败，请检查原因或再次运行git_pull.sh...


```

大佬，早上pull的docker，现在shell可以更新，但是有时候更新失败会报“检测到package.json有变化，运行 npm install”
这是什么情况呢？

lxk的脚本私有化之后，现在是没有办法拉取吗？

**Comment by dockere** [comment]
> ```
> 
> --------------------------------------------------------------
> 
> 系统时间：2021-02-22 13:11:46
> 
> SHELL脚本目录：/jd
> 
> JS脚本目录：/jd/scripts
> 
> --------------------------------------------------------------
> 
> 更新shell脚本，原地址：https://github.com/dockere/jd-base
> 
> Fetching origin
> fatal: unable to access 'https://github.com/dockere/jd-base/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443
> error: Could not fetch origin
> HEAD is now at e29d603 Update Dockerfile
> 
> shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> 
> js脚本更新完成...
> 
> 检测到package.json有变化，运行 npm install...
> 
> audited 207 packages in 6.022s
> 
> 11 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> 
> /usr/local/bin/git_pull: line 217: [: -eq: unary operator expected
> ```
> 
> 
> ```
> --------------------------------------------------------------
> 
> Fetching origin
> Username for 'https://gitee.com':
> Password for 'https://gitee.com':
> remote: Unauthorized
> fatal: Authentication failed for 'https://gitee.com/lxk0301/jd_scripts/'
> error: Could not fetch origin
> HEAD is now at 978ef05 jd_price.js
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...
> ```
> 
> 
> 大佬，早上pull的docker，现在shell可以更新，但是有时候更新失败会报“检测到package.json有变化，运行 npm install”
> 
> 这是什么情况呢？
> 
> 
> lxk的脚本私有化之后，现在是没有办法拉取吗？

你这个应该调用的旧镜像，查下文档如何删镜像吧，昨天下午4点的镜像已经内置lxk库的密钥了

**Comment by encoo** [comment]
> > ```
> > 
> > --------------------------------------------------------------
> > 
> > 系统时间：2021-02-22 13:11:46
> > 
> > SHELL脚本目录：/jd
> > 
> > JS脚本目录：/jd/scripts
> > 
> > --------------------------------------------------------------
> > 
> > 更新shell脚本，原地址：https://github.com/dockere/jd-base
> > 
> > Fetching origin
> > fatal: unable to access 'https://github.com/dockere/jd-base/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443
> > error: Could not fetch origin
> > HEAD is now at e29d603 Update Dockerfile
> > 
> > shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> > 
> > js脚本更新完成...
> > 
> > 检测到package.json有变化，运行 npm install...
> > 
> > audited 207 packages in 6.022s
> > 
> > 11 packages are looking for funding
> >   run `npm fund` for details
> > 
> > found 0 vulnerabilities
> > 
> > 
> > /usr/local/bin/git_pull: line 217: [: -eq: unary operator expected
> > ```
> > 
> > 
> > ```
> > --------------------------------------------------------------
> > 
> > Fetching origin
> > Username for 'https://gitee.com':
> > Password for 'https://gitee.com':
> > remote: Unauthorized
> > fatal: Authentication failed for 'https://gitee.com/lxk0301/jd_scripts/'
> > error: Could not fetch origin
> > HEAD is now at 978ef05 jd_price.js
> > 
> > js脚本更新失败，请检查原因或再次运行git_pull.sh...
> > ```
> > 
> > 
> > 大佬，早上pull的docker，现在shell可以更新，但是有时候更新失败会报“检测到package.json有变化，运行 npm install”
> > 这是什么情况呢？
> > lxk的脚本私有化之后，现在是没有办法拉取吗？
> 
> 你这个应该调用的旧镜像，查下文档如何删镜像吧，昨天下午4点的镜像已经内置lxk库的密钥了

感谢大佬，完整删除原镜像，重新拉取了noobx/jd:py镜像后，已经可以正常更新了
