### ISSUE TITLE
临时屏蔽某个cookie

### ISSUE THREAD

**Issue by VectorZhao** [dockere/jd-base#29]
在config.sh文件中添加了如下设置：
case $1 in
  jd_family)
    TempBlockCookie="3"      # 账号3不玩东东农场
    ;;
  jd_dreamFactory | jd_jdfactory)
    TempBlockCookie="3"      # 账号3不玩京喜工厂和东东工厂
    ;;
esac

但是在运行相关脚本的时候，账号3依然会玩这些游戏。
请问是哪里设置有问题？谢谢大佬

**Comment by dockere** [comment]
```
case $1 in
jd_family | jd_dreamFactory | jd_jdfactory)
   TempBlockCookie="3" 
   ;;
esac
```
>试试

**Comment by VectorZhao** [comment]
> ```
> case $1 in
> jd_family | jd_dreamFactory | jd_jdfactory)
>    TempBlockCookie="3" 
>    ;;
> esac
> ```
> 
> > 试试
不行，重启jd容器运行，还是会玩这些游戏。。。。。。。。。。。。。

**Comment by dockere** [comment]
> > ```
> > case $1 in
> > jd_family | jd_dreamFactory | jd_jdfactory)
> >    TempBlockCookie="3" 
> >    ;;
> > esac
> > ```
> > 
> > 
> > > 试试
> > > 不行，重启jd容器运行，还是会玩这些游戏。。。。。。。。。。。。。

我用这个可以。仔细看下config配置

**Comment by VectorZhao** [comment]
> > > ```
> > > case $1 in
> > > jd_family | jd_dreamFactory | jd_jdfactory)
> > >    TempBlockCookie="3" 
> > >    ;;
> > > esac
> > > ```
> > > 
> > > 
> > > > 试试
> > > > 不行，重启jd容器运行，还是会玩这些游戏。。。。。。。。。。。。。
> 
> 我用这个可以。仔细看下config配置

感谢大佬解答。
我再研究下吧，不知道哪里写错了，我也是复制粘贴到相应位置。

**Comment by lautokwah** [comment]
试试把 esac 下面的 TempBlockCookie="" 这行注释掉。

**Comment by VectorZhao** [comment]
> 试试把 esac 下面的 TempBlockCookie="" 这行注释掉。

case $1 in
jd_family | jd_dreamFactory | jd_jdfactory)
   TempBlockCookie="3" 
   ;;
esac

# TempBlockCookie="3"      # 账号3不玩 家庭号，京喜工厂，京东工厂

这样设置，然后运行docker exec -it jd bash jd jdfactory now，账号3是会执行京东工厂的

**Comment by VectorZhao** [comment]
> 试试把 esac 下面的 TempBlockCookie="" 这行注释掉。

我懂了，是不是如果运行docker exec -it jd bash jd jdfactory now这个命令，脚本肯定会执行所有没有屏蔽的cookie，如果是docker自己分配任务，case命令才会生效。

**Comment by flylic** [comment]
> > 试试把 esac 下面的 TempBlockCookie="" 这行注释掉。
> 
> 我懂了，是不是如果运行docker exec -it jd bash jd jdfactory now这个命令，脚本肯定会执行所有没有屏蔽的cookie，如果是docker自己分配任务，case命令才会生效。

我的理解是手动执行脚步是不受config.sh配置控制的，你看看自动运行的日志里面的日志是否还是会运行屏蔽的账号。
