### ISSUE TITLE
大佬，N1盒子拉取镜像不能正常使用

### ISSUE THREAD

**Issue by Luxuslaerm** [dockere/jd-base#3]
容器是运行起来了，但是点击扫码获取cookie弹框报错了

**Comment by dockere** [comment]
> 容器是运行起来了，但是点击扫码获取cookie弹框报错了

我测试is正常的，可能没有正常拉去镜像导致的。删除容器重新来一次看看

**Comment by Luxuslaerm** [comment]
![image](https://user-images.githubusercontent.com/9360302/107232623-94263700-6a5c-11eb-91f0-11f1857a741b.png)
依旧不行

docker logs -f jd 看到一条错误
`

Fetching origin
fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': Failed to connect to gitee.com port 443: Connection refused
error: Could not fetch origin
HEAD is now at 7981ecb update

js脚本更新失败，请检查原因或再次运行git_pull.sh...
`

**Comment by dockere** [comment]
> ![image](https://user-images.githubusercontent.com/9360302/107232623-94263700-6a5c-11eb-91f0-11f1857a741b.png)
> 依旧不行
> 
> docker logs -f jd 看到一条错误
> `
> 
> Fetching origin
> fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': Failed to connect to gitee.com port 443: Connection refused
> error: Could not fetch origin
> HEAD is now at 7981ecb update
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...
> `

日志显示你网络无法访问gitee；但貌似这条LOG和扫码没有关联

**Comment by dockere** [comment]
> ![image](https://user-images.githubusercontent.com/9360302/107232623-94263700-6a5c-11eb-91f0-11f1857a741b.png)
> 依旧不行
> 
> docker logs -f jd 看到一条错误
> `
> 
> Fetching origin
> fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': Failed to connect to gitee.com port 443: Connection refused
> error: Could not fetch origin
> HEAD is now at 7981ecb update
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...
> `

本机Docker测试了下，都正常，应该是你设备没有网络的原因，因为获取二维码是要请求京东的API的；你Lxk的库也无法正常拉去；建议执行：ping baidu.com （PING百度）或执行：curl cip.cc（查看外网）；检查是否有网络

**Comment by Luxuslaerm** [comment]
> > ![image](https://user-images.githubusercontent.com/9360302/107232623-94263700-6a5c-11eb-91f0-11f1857a741b.png)
> > 依旧不行
> > docker logs -f jd 看到一条错误
> > `
> > Fetching origin
> > fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': Failed to connect to gitee.com port 443: Connection refused
> > error: Could not fetch origin
> > HEAD is now at 7981ecb update
> > js脚本更新失败，请检查原因或再次运行git_pull.sh...
> > `
> 
> 本机Docker测试了下，都正常，应该是你设备没有网络的原因，因为获取二维码是要请求京东的API的；你Lxk的库也无法正常拉去；建议执行：ping baidu.com （PING百度）或执行：curl cip.cc（查看外网）；检查是否有网络

果然是的，容器里面ping不通，运行容器时使用

`--network host`

就可以了，感谢大佬指点。
