### ISSUE TITLE
互助码格式好像变了？

### ISSUE THREAD

**Issue by qq34347476** [dockere/jd-base#33]
京喜农场

互助码格式变更，请重新填写 ‼️‼️

这个是要重新 搞成啥样 ？？

**Comment by dockere** [comment]
> 京喜农场
> 
> 互助码格式变更，请重新填写 ‼️‼️
> 
> 这个是要重新 搞成啥样 ？？

运行脚本log提示的嘛

**Comment by qq34347476** [comment]
对的，咋改这个？

**Comment by dockere** [comment]
> 对的，咋改这个？

重新获取

**Comment by qq34347476** [comment]
https://gitee.com/lxk0301/jd_docker/tree/master/docker 看到有个更新：

2021-02-10更新 docker-compose里面,填写环境变量 SHARE_CODE_FILE=/scripts/logs/sharecode.log, 多账号可实现自己互助(只限sharecode.log日志里面几个活动)

这大大的方便了自己号码的互助

请问本项目的docker是否支持，如果支持如何使用？

**Comment by kissfast** [comment]
京喜农场每次种，互助码都是会变化的，需要运行一次脚本后，然后看log
