### ISSUE TITLE
请问一下时间设定list文件为啥设置了root权限？

### ISSUE THREAD

**Issue by hecarli555** [dockere/jd-base#37]
请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限

**Comment by dockere** [comment]
> 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限

crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。

**Comment by hecarli555** [comment]
> > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> 
> crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。

前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。

**Comment by dockere** [comment]
> > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > 
> > 
> > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> 
> 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。

解决了么

**Comment by hecarli555** [comment]
> > > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > > 
> > > 
> > > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> > 
> > 
> > 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。
> 
> 解决了么

不得行，我单独把list的权限开放给我自己的账号，此时可以scp修改了，但是我执行gitpull后，我账号的权限会被刷掉，然后再去修改的话又提示权限不足。。。。

**Comment by dockere** [comment]
> > > > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > > > 
> > > > 
> > > > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> > > 
> > > 
> > > 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。
> > 
> > 
> > 解决了么
> 
> 不得行，我单独把list的权限开放给我自己的账号，此时可以scp修改了，但是我执行gitpull后，我账号的权限会被刷掉，然后再去修改的话又提示权限不足。。。。

dockr构建镜像的时候没有特地的更改某个文件夹或文件的权限的，如你不是docker请排查下系统原因。

**Comment by hecarli555** [comment]
> > > > > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > > > > 
> > > > > 
> > > > > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> > > > 
> > > > 
> > > > 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。
> > > 
> > > 
> > > 解决了么
> > 
> > 
> > 不得行，我单独把list的权限开放给我自己的账号，此时可以scp修改了，但是我执行gitpull后，我账号的权限会被刷掉，然后再去修改的话又提示权限不足。。。。
> 
> dockr构建镜像的时候没有特地的更改某个文件夹或文件的权限的，如你不是docker请排查下系统原因。

我的就是群辉docker的，之前改都是好好的，今天修改就提示这个，如图
![image](https://user-images.githubusercontent.com/76683744/109151054-a61a1080-77a4-11eb-9dfa-ff59a859b534.png)

**Comment by dockere** [comment]
> > > > > > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > > > > > 
> > > > > > 
> > > > > > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> > > > > 
> > > > > 
> > > > > 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。
> > > > 
> > > > 
> > > > 解决了么
> > > 
> > > 
> > > 不得行，我单独把list的权限开放给我自己的账号，此时可以scp修改了，但是我执行gitpull后，我账号的权限会被刷掉，然后再去修改的话又提示权限不足。。。。
> > 
> > 
> > dockr构建镜像的时候没有特地的更改某个文件夹或文件的权限的，如你不是docker请排查下系统原因。
> 
> 我的就是群辉docker的，之前改都是好好的，今天修改就提示这个，如图
> ![image](https://user-images.githubusercontent.com/76683744/109151054-a61a1080-77a4-11eb-9dfa-ff59a859b534.png)

大致就是权限问题了；web是更改完自动生效的。试下web吧。

**Comment by hecarli555** [comment]
> > > > > > > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > > > > > > 
> > > > > > > 
> > > > > > > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> > > > > > 
> > > > > > 
> > > > > > 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。
> > > > > 
> > > > > 
> > > > > 解决了么
> > > > 
> > > > 
> > > > 不得行，我单独把list的权限开放给我自己的账号，此时可以scp修改了，但是我执行gitpull后，我账号的权限会被刷掉，然后再去修改的话又提示权限不足。。。。
> > > 
> > > 
> > > dockr构建镜像的时候没有特地的更改某个文件夹或文件的权限的，如你不是docker请排查下系统原因。
> > 
> > 
> > 我的就是群辉docker的，之前改都是好好的，今天修改就提示这个，如图
> > ![image](https://user-images.githubusercontent.com/76683744/109151054-a61a1080-77a4-11eb-9dfa-ff59a859b534.png)
> 
> 大致就是权限问题了；web是更改完自动生效的。试下web吧。

web是没问题的，就是web端口一直没做映射嘛，在外面上班的时候摸鱼用用scp就好了，映射太多端口心里不踏实。。。。。

**Comment by dockere** [comment]
> > > > > > > > > 请问一下时间设定list文件为啥设置了root权限？没映射控制台端口，用winscp来修改list文件提示权限不够。。。这样太不方便了，希望下方权限
> > > > > > > > 
> > > > > > > > 
> > > > > > > > crontab.list这个吗？644权限是有写入权限的，自己检查下是否root权限吧。
> > > > > > > 
> > > > > > > 
> > > > > > > 前几天修改都没这个情况出现的。。。不知道今天怎么会提示权限不足，突然修改权限提高了。。。
> > > > > > 
> > > > > > 
> > > > > > 解决了么
> > > > > 
> > > > > 
> > > > > 不得行，我单独把list的权限开放给我自己的账号，此时可以scp修改了，但是我执行gitpull后，我账号的权限会被刷掉，然后再去修改的话又提示权限不足。。。。
> > > > 
> > > > 
> > > > dockr构建镜像的时候没有特地的更改某个文件夹或文件的权限的，如你不是docker请排查下系统原因。
> > > 
> > > 
> > > 我的就是群辉docker的，之前改都是好好的，今天修改就提示这个，如图
> > > ![image](https://user-images.githubusercontent.com/76683744/109151054-a61a1080-77a4-11eb-9dfa-ff59a859b534.png)
> > 
> > 
> > 大致就是权限问题了；web是更改完自动生效的。试下web吧。
> 
> web是没问题的，就是web端口一直没做映射嘛，在外面上班的时候摸鱼用用scp就好了，映射太多端口心里不踏实。。。。。

好吧，你自己看下吧
