### ISSUE TITLE
git pull报错一大堆

### ISSUE THREAD

**Issue by binge8** [dockere/jd-base#38]
下午开始的
[报错.txt](https://github.com/dockere/jd-base/files/6043045/default.txt)

**Comment by dockere** [comment]
> 下午开始的
> [报错.txt](https://github.com/dockere/jd-base/files/6043045/default.txt)

自己确认下配置文件吧

**Comment by binge8** [comment]
> > 下午开始的
> > [报错.txt](https://github.com/dockere/jd-base/files/6043045/default.txt)
> 
> 自己确认下配置文件吧

好吧我重新设置一边，不过控制面板的对比工具看好像没问题

**Comment by dockere** [comment]
> > > 下午开始的
> > > [报错.txt](https://github.com/dockere/jd-base/files/6043045/default.txt)
> > 
> > 
> > 自己确认下配置文件吧
> 
> 好吧我重新设置一边，不过控制面板的对比工具看好像没问题

enen，确认下配置文件。

**Comment by binge8** [comment]
> > > > 下午开始的
> > > > [报错.txt](https://github.com/dockere/jd-base/files/6043045/default.txt)
> > > 
> > > 
> > > 自己确认下配置文件吧
> > 
> > 
> > 好吧我重新设置一边，不过控制面板的对比工具看好像没问题
> 
> enen，确认下配置文件。

果然是配置文件问题。谢谢。
