### ISSUE TITLE
扫码获取cookie为什么显示objective

### ISSUE THREAD

**Issue by lfscqk67** [dockere/jd-base#39]
![image](https://user-images.githubusercontent.com/37235589/109263139-b631fe80-783d-11eb-9b5c-4507eed4dd2e.png)

**Comment by dockere** [comment]
容器无网；看下这条Issues:https://github.com/dockere/jd-base/issues/3

**Comment by lfscqk67** [comment]
> 容器无网；看下这条Issues:#3

啊，打开openclash可以了

**Comment by dockere** [comment]
hao
d
