### ISSUE TITLE
 拉不到库，需要怎么处理。

### ISSUE THREAD

**Issue by YUDIDIFEI** [dockere/jd-base#4]
我需要怎么操作才可以更新，大佬

fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': OpenSSL SSL_con                                                                                                                                                                             nect: SSL_ERROR_SYSCALL in connection to gitee.com:443
error: Could not fetch origin
HEAD is now at 7981ecb update

**Comment by dockere** [comment]
> 我需要怎么操作才可以更新，大佬
> 
> fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': OpenSSL SSL_con nect: SSL_ERROR_SYSCALL in connection to gitee.com:443
> error: Could not fetch origin
> HEAD is now at 7981ecb update

[](https://github.com/dockere/jd-base/issues/3)
建议看下这条Issues
