### ISSUE TITLE
东东爱消除这个游戏，脚本不做任务吗？

### ISSUE THREAD

**Issue by nbnb666888** [dockere/jd-base#41]
我导出所有互助码，发现没有东东爱消除这个游戏的互助码，手机查看 任务也没做，请问是因为没有这个游戏的脚本吗？

**Comment by dockere** [comment]
> 我导出所有互助码，发现没有东东爱消除这个游戏的互助码，手机查看 任务也没做，请问是因为没有这个游戏的脚本吗？

没有；容易黑号。

**Comment by nbnb666888** [comment]
好的 谢谢大佬，关闭这个issue吧
