### ISSUE TITLE
请问另外的py脚本怎么用

### ISSUE THREAD

**Issue by landcruser** [dockere/jd-base#42]
我看脚本的scripts2和3已经拉取了代码，如何执行？进去python环境执行没有反应，也不输出log，还有如何给py脚本添加定时执行？

**Comment by kangwenhang** [comment]
scripts2是py脚本的目录，目前只有喜马拉雅，执行命令是docker exce -it jd bash jd xmly py，参考https://github.com/dockere/jd-base/blob/py/sample/docker.list.sample这里面的去设置cron，先部署好config中的export XMLY_SPEED_COOKIE=""

**Comment by landcruser** [comment]
> scripts2是py脚本的目录，目前只有喜马拉雅，执行命令是docker exce -it jd bash jd xmly py，参考https://github.com/dockere/jd-base/blob/py/sample/docker.list.sample 这里面的去设置cron，先部署好config中的export XMLY_SPEED_COOKIE=""

感谢大佬热心解答
