### ISSUE TITLE
docker arm用户更新失败

### ISSUE THREAD

**Issue by qaz88q11** [dockere/jd-base#43]
py脚本更新失败，我群里所有arm用户全是如此  scripts2里面空白

**Comment by dockere** [comment]
截图

**Comment by kangwenhang** [comment]
今天才出现的吗，git_pull看看有没有报错

**Comment by qaz88q11** [comment]
更新LXK大佬脚本


Fetching origin
HEAD is now at 7fb06e5 debug


克隆Zero-S1/xmly_speed脚本，地址：https://github.com/Zero-S1/xmly_speed


fatal: destination path '/jd/scripts2' already exists and is not an empty directory.


更新AutoSignMachine脚本


Fetching origin
HEAD is now at 2e3f759 同步更新脚本


js脚本更新完成...


py脚本更新失败，请检查原因或再次运行git_pull.sh...


AutoSignMachine的js脚本更新完成...







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dockere/jd-base"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月27日(星期六) 晚上7:56
收件人:&nbsp;"dockere/jd-base"<jd-base@noreply.github.com&gt;;
抄送:&nbsp;"Skk"<13680714@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dockere/jd-base] docker arm用户更新失败 (#43)





 
今天才出现的吗，git_pull看看有没有报错

**Comment by qaz88q11** [comment]
> 更新LXK大佬脚本获取原始HEAD现在位于7fb06e5调试克隆Zero-S1 / xmly_speed脚本，地址：[https](https://github.com/Zero-S1/xmly_speed) : [//github.com/Zero-S1/xmly_speed](https://github.com/Zero-S1/xmly_speed) 致命：目标路径'/ jd / scripts2'已经存在并且已经存在不是一个空目录。更新AutoSignMachine脚本提取源HEAD现在位于2e3f759同步更新脚本js脚本更新完成... py脚本更新失败，请检查原因或再次运行git_pull.sh ... AutoSignMachine的js脚本更新完成...
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dockere/jd-base" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月27日(星期六) 晚上7:56 收件人:&nbsp;"dockere/jd-base"<jd-base@noreply.github.com&gt;; 抄送:&nbsp;"Skk"<13680714@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dockere/jd-base] docker arm用户更新失败 (#43) 今天才出现的吗，git_pull看看有没有报错 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

今天出现的，好多arm用户出现此情况

**Comment by kangwenhang** [comment]
> LXK 与生并列取源头现在位于 7fb06e5 试探性零点 S1/xmly_speed，：https://github.com/Zero-S1/xmly_speed致命：目的地路径"/jd/scripts2"已经存在，并且不是一个空目录。自动签名机器获取起源头现在是在2e3f759高频。。。py · 斯派姆 · 比特， 乌姆· 乌姆· 多git_pull.sh自动签名机器与人交易。。。
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dockere/jd-base" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月27日(星期六) 晚上7:56 收件人:&nbsp;"dockere/jd-base"<jd-base@noreply.github.com&gt;; 抄送:&nbsp;"Skk"<13680714@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dockere/jd-base] docker arm用户更新失败 (#43) 今天才出现的吗，git_pull看看有没有报错 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是不是把/jd/scripts2文件夹给映射出来了

**Comment by qaz88q11** [comment]
> > LXK与生并列取源头现在位于7fb06e5试探性零点S1 / xmly_speed ，：[https://github.com/Zero-S1/xmly_speed致命：目标路径“ / jd / scripts2”已经存在，并且不是一个空目录。自动签名机器获取起源头现在是在2e3f759高频... PY](https://github.com/Zero-S1/xmly_speed%E8%87%B4%E5%91%BD%EF%BC%9A%E7%9B%AE%E7%9A%84%E5%9C%B0%E8%B7%AF%E5%BE%84%22/jd/scripts2%22%E5%B7%B2%E7%BB%8F%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%B9%B6%E4%B8%94%E4%B8%8D%E6%98%AF%E4%B8%80%E4%B8%AA%E7%A9%BA%E7%9B%AE%E5%BD%95%E3%80%82%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%90%8D%E6%9C%BA%E5%99%A8%E8%8E%B7%E5%8F%96%E8%B5%B7%E6%BA%90%E5%A4%B4%E7%8E%B0%E5%9C%A8%E6%98%AF%E5%9C%A82e3f759%E9%AB%98%E9%A2%91%E3%80%82%E3%80%82%E3%80%82py) ·斯派姆·比特，乌姆·乌姆·多git_pull.sh自动签名机器与人交易... 
> > [...](#) 
> > ----- -------------原始邮件------------------发件人：“ dockere / jd-base” < [notifications@github.com](mailto:notifications@github.com) >; 发送时间：2021年2月27日（星期六）晚上7:56收件人：“ dockere / jd-base” < [jd-base@noreply.github.com](mailto:jd-base@noreply.github.com) >; 抄送：“ Skk” < [13680714@qq.com](mailto:13680714@qq.com) >;“作者” < [author@noreply.github.com](mailto:author@noreply.github.com) >; 主题：回复：[dockere / jd-base] docker arm用户更新失败（[＃43](https://github.com/dockere/jd-base/issues/43)）今天才出现的吗，git_pull看看有没有报错 直接回复此电子邮件，在GitHub上查看，
> 
> 是不是把/ jd / scripts2文件夹给映射出来了

docker run -dit \
-v /root/jd/config:/jd/config \
-v /root/jd/log:/jd/log \
-v /root/jd/scripts:/jd/scripts \
-v /root/jd/scripts2/docker:/jd/scripts2/docker \
-v /root/jd/git_pull.sh:/git_pull.sh \
--network host \
--name jd \
--hostname jd \
--restart always \
noobx/jd:py
大佬看看是不是哪里出错
旁路由 这样弄的

**Comment by kangwenhang** [comment]
> > > LXK与生并列取源头现在位于7fb06e5试探性零点S1 / xmly_speed ，：[https://github.com/Zero-S1/xmly_speed致命：目标路径“ / jd / scripts2”已经存在，并且不是一个空目录。自动签名机器获取起源头现在是在2e3f759高频... PY](https://github.com/Zero-S1/xmly_speed%E8%87%B4%E5%91%BD%EF%BC%9A%E7%9B%AE%E7%9A%84%E5%9C%B0%E8%B7%AF%E5%BE%84%22/jd/scripts2%22%E5%B7%B2%E7%BB%8F%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%B9%B6%E4%B8%94%E4%B8%8D%E6%98%AF%E4%B8%80%E4%B8%AA%E7%A9%BA%E7%9B%AE%E5%BD%95%E3%80%82%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%90%8D%E6%9C%BA%E5%99%A8%E8%8E%B7%E5%8F%96%E8%B5%B7%E6%BA%90%E5%A4%B4%E7%8E%B0%E5%9C%A8%E6%98%AF%E5%9C%A82e3f759%E9%AB%98%E9%A2%91%E3%80%82%E3%80%82%E3%80%82py) ·斯派姆·比特，乌姆·乌姆·多git_pull.sh自动签名机器与人交易...
> > > [...](#)
> > > ----- -------------原始邮件------------------发件人：“ dockere / jd-base” < [notifications@github.com](mailto:notifications@github.com) >; 发送时间：2021年2月27日（星期六）晚上7:56收件人：“ dockere / jd-base” < [jd-base@noreply.github.com](mailto:jd-base@noreply.github.com) >; 抄送：“ Skk” < [13680714@qq.com](mailto:13680714@qq.com) >;“作者” < [author@noreply.github.com](mailto:author@noreply.github.com) >; 主题：回复：[dockere / jd-base] docker arm用户更新失败（[＃43](https://github.com/dockere/jd-base/issues/43)）今天才出现的吗，git_pull看看有没有报错 直接回复此电子邮件，在GitHub上查看，
> > 
> > 
> > 是不是把/ jd / scripts2文件夹给映射出来了
> 
> docker run -dit
> -v /root/jd/config:/jd/config
> -v /root/jd/log:/jd/log
> -v /root/jd/scripts:/jd/scripts
> -v /root/jd/scripts2/docker:/jd/scripts2/docker
> -v /root/jd/git_pull.sh:/git_pull.sh
> --network host
> --name jd
> --hostname jd
> --restart always
> noobx/jd:py
> 大佬看看是不是哪里出错
> 旁路由 这样弄的

真确代码：
docker run -dit
-v /root/jd/config:/jd/config
-v /root/jd/log:/jd/log
-v /root/jd/scripts:/jd/scripts
-v /root/jd/scripts2/docker:/jd/scripts2
-v /root/jd/git_pull.sh:/git_pull.sh
--network host
--name jd
--hostname jd
--restart always
noobx/jd:py

**Comment by kangwenhang** [comment]
> > > LXK与生并列取源头现在位于7fb06e5试探性零点S1 / xmly_speed ，：[https://github.com/Zero-S1/xmly_speed致命：目标路径“ / jd / scripts2”已经存在，并且不是一个空目录。自动签名机器获取起源头现在是在2e3f759高频... PY](https://github.com/Zero-S1/xmly_speed%E8%87%B4%E5%91%BD%EF%BC%9A%E7%9B%AE%E7%9A%84%E5%9C%B0%E8%B7%AF%E5%BE%84%22/jd/scripts2%22%E5%B7%B2%E7%BB%8F%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%B9%B6%E4%B8%94%E4%B8%8D%E6%98%AF%E4%B8%80%E4%B8%AA%E7%A9%BA%E7%9B%AE%E5%BD%95%E3%80%82%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%90%8D%E6%9C%BA%E5%99%A8%E8%8E%B7%E5%8F%96%E8%B5%B7%E6%BA%90%E5%A4%B4%E7%8E%B0%E5%9C%A8%E6%98%AF%E5%9C%A82e3f759%E9%AB%98%E9%A2%91%E3%80%82%E3%80%82%E3%80%82py) ·斯派姆·比特，乌姆·乌姆·多git_pull.sh自动签名机器与人交易...
> > > [...](#)
> > > ----- -------------原始邮件------------------发件人：“ dockere / jd-base” < [notifications@github.com](mailto:notifications@github.com) >; 发送时间：2021年2月27日（星期六）晚上7:56收件人：“ dockere / jd-base” < [jd-base@noreply.github.com](mailto:jd-base@noreply.github.com) >; 抄送：“ Skk” < [13680714@qq.com](mailto:13680714@qq.com) >;“作者” < [author@noreply.github.com](mailto:author@noreply.github.com) >; 主题：回复：[dockere / jd-base] docker arm用户更新失败（[＃43](https://github.com/dockere/jd-base/issues/43)）今天才出现的吗，git_pull看看有没有报错 直接回复此电子邮件，在GitHub上查看，
> > 
> > 
> > 是不是把/ jd / scripts2文件夹给映射出来了
> 
> docker run -dit
> -v /root/jd/config:/jd/config
> -v /root/jd/log:/jd/log
> -v /root/jd/scripts:/jd/scripts
> -v /root/jd/scripts2/docker:/jd/scripts2/docker
> -v /root/jd/git_pull.sh:/git_pull.sh
> --network host
> --name jd
> --hostname jd
> --restart always
> noobx/jd:py
> 大佬看看是不是哪里出错
> 旁路由 这样弄的

怎么看怎么有问题，你看下py分支里怎么写的

**Comment by kangwenhang** [comment]
> > > LXK与生并列取源头现在位于7fb06e5试探性零点S1 / xmly_speed ，：[https://github.com/Zero-S1/xmly_speed致命：目标路径“ / jd / scripts2”已经存在，并且不是一个空目录。自动签名机器获取起源头现在是在2e3f759高频... PY](https://github.com/Zero-S1/xmly_speed%E8%87%B4%E5%91%BD%EF%BC%9A%E7%9B%AE%E7%9A%84%E5%9C%B0%E8%B7%AF%E5%BE%84%22/jd/scripts2%22%E5%B7%B2%E7%BB%8F%E5%AD%98%E5%9C%A8%EF%BC%8C%E5%B9%B6%E4%B8%94%E4%B8%8D%E6%98%AF%E4%B8%80%E4%B8%AA%E7%A9%BA%E7%9B%AE%E5%BD%95%E3%80%82%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%90%8D%E6%9C%BA%E5%99%A8%E8%8E%B7%E5%8F%96%E8%B5%B7%E6%BA%90%E5%A4%B4%E7%8E%B0%E5%9C%A8%E6%98%AF%E5%9C%A82e3f759%E9%AB%98%E9%A2%91%E3%80%82%E3%80%82%E3%80%82py) ·斯派姆·比特，乌姆·乌姆·多git_pull.sh自动签名机器与人交易...
> > > [...](#)
> > > ----- -------------原始邮件------------------发件人：“ dockere / jd-base” < [notifications@github.com](mailto:notifications@github.com) >; 发送时间：2021年2月27日（星期六）晚上7:56收件人：“ dockere / jd-base” < [jd-base@noreply.github.com](mailto:jd-base@noreply.github.com) >; 抄送：“ Skk” < [13680714@qq.com](mailto:13680714@qq.com) >;“作者” < [author@noreply.github.com](mailto:author@noreply.github.com) >; 主题：回复：[dockere / jd-base] docker arm用户更新失败（[＃43](https://github.com/dockere/jd-base/issues/43)）今天才出现的吗，git_pull看看有没有报错 直接回复此电子邮件，在GitHub上查看，
> > 
> > 
> > 是不是把/ jd / scripts2文件夹给映射出来了
> 
> docker run -dit
> -v /root/jd/config:/jd/config
> -v /root/jd/log:/jd/log
> -v /root/jd/scripts:/jd/scripts
> -v /root/jd/scripts2/docker:/jd/scripts2/docker
> -v /root/jd/git_pull.sh:/git_pull.sh
> --network host
> --name jd
> --hostname jd
> --restart always
> noobx/jd:py
> 大佬看看是不是哪里出错
> 旁路由 这样弄的

旁路由这样写才对
-v /root/jd/config:/jd/config
-v /root/jd/log:/jd/log
-v /root/jd/scripts:/jd/scripts
-v /root/jd/scripts2:/jd/scripts2
--network host
--name jd
--hostname jd
--restart always
noobx/jd:py

**Comment by qaz88q11** [comment]
感谢大佬的耐心讲解，以完美解决  持续关注大佬的更新
