### ISSUE TITLE
lxk财富岛助力参数

### ISSUE THREAD

**Issue by 2375399351** [dockere/jd-base#46]
`JDCFD_SHARECODES`      |  京喜财富岛
这个就是了，能不能更新下config
![F893991B-60A1-470E-B039-7D9EDDC7CB00](https://user-images.githubusercontent.com/34334506/109466478-baac2080-7aa4-11eb-8c24-18a3dcd43a02.png)

**Comment by dockere** [comment]
有了呀，手动对比过去就好了

**Comment by 2375399351** [comment]
> 有了呀，手动对比过去就好了

我说错了，是得更新jd.sh这个文件
export JDCFD_SHARECODES =$(Combin_Sub ForOtherJDGLOBAL)
这个不更新，config上面加入了也没用的
![50C51A12-53B3-4E9B-B793-1B60DBCE6998](https://user-images.githubusercontent.com/34334506/109467017-8a18b680-7aa5-11eb-9cd5-fe9d23bb65b0.png)

**Comment by 2375399351** [comment]
> 有了呀，手动对比过去就好了

奇怪了，我看你库里的jd.sh更新了，但是我这本地不知道为什么没有更新，但是已经pull了，config也变了啊……

**Comment by dockere** [comment]
> > 有了呀，手动对比过去就好了
> 
> 我说错了，是得更新jd.sh这个文件
> export JDCFD_SHARECODES =$(Combin_Sub ForOtherJDGLOBAL)
> 这个不更新，config上面加入了也没用的
> ![50C51A12-53B3-4E9B-B793-1B60DBCE6998](https://user-images.githubusercontent.com/34334506/109467017-8a18b680-7aa5-11eb-9cd5-fe9d23bb65b0.png)

你用的谁的？你这个jd.sh不是我库里的，昨天就更新上去了！js.sh在库里自己都可以看到的

**Comment by dockere** [comment]
> > 有了呀，手动对比过去就好了
> 
> 奇怪了，我看你库里的jd.sh更新了，但是我这本地不知道为什么没有更新，但是已经pull了，config也变了啊……

嗯，好好检查下哦
