### ISSUE TITLE
大佬，可以加一个宠汪汪助力码的配置吗？

### ISSUE THREAD

**Issue by felix-wj** [dockere/jd-base#50]
在jd_joy_run.js里看到有读取配置的代码
![UAP7)_7YU62UG~PEI4U58QF](https://user-images.githubusercontent.com/13774998/109815185-5470fa80-7c6a-11eb-8e6e-9f938d283cc0.png)

**Comment by dockere** [comment]
> 在jd_joy_run.js里看到有读取配置的代码
> ![UAP7)_7YU62UG~PEI4U58QF](https://user-images.githubusercontent.com/13774998/109815185-5470fa80-7c6a-11eb-8e6e-9f938d283cc0.png)

移动端boxjs用的

**Comment by felix-wj** [comment]
node环境可以加吗

**Comment by dockere** [comment]
等你PR

**Comment by felix-wj** [comment]
OK
