### ISSUE TITLE
自己写了两个脚本，完美兼容

### ISSUE THREAD

**Issue by qq34347476** [dockere/jd-base#51]
一个互助码格式化自动写入config
一个宠汪汪账号下赛跑互助

大佬可以采纳下～在我仓库里

**Comment by dockere** [comment]
> 一个互助码格式化自动写入config
> 一个宠汪汪账号下赛跑互助
> 
> 大佬可以采纳下～在我仓库里

如果是shell的可以直接pr的。

**Comment by qq34347476** [comment]
js的……diy跟config要配置变量

**Comment by dockere** [comment]
> js的……diy跟config要配置变量

好的，我看看，可以去掉互助直接PR的；lxk是不希望改脚本里的PIN的，貌似之前的加密改回去了。

**Comment by qq34347476** [comment]
嗯，大佬可以先看下，我不会shell只会js……所以只能弄到这样……

**Comment by dockere** [comment]
> 嗯，大佬可以先看下，我不会shell只会js……所以只能弄到这样……

- - 好，感谢。但改js貌似不太行。

**Comment by dockere** [comment]
> 嗯，大佬可以先看下，我不会shell只会js……所以只能弄到这样……

或者你可以PR给lxk。这边直接添加这个变量就行，

**Comment by qq34347476** [comment]
js实现互助码按格式修改config，实现docker下所有账户相互互助，
lxy的宠汪汪 互助年前失效到今天，我才改写了这个宠汪汪

**Comment by dockere** [comment]
> js实现互助码按格式修改config，实现docker下所有账户相互互助，
> lxy的宠汪汪 互助年前失效到今天，我才改写了这个宠汪汪

嗯，所以pr给lxk更为妥当。

**Comment by qq34347476** [comment]
lxy设计自己填，设计默认互助……等于否掉docker账号自给自足……水平比我也高多了，我能实现想到，他应该早就能想到而没这么做吧……

**Comment by dockere** [comment]
> lxy设计自己填，设计默认互助……等于否掉docker账号自给自足……水平比我也高多了，我能实现想到，他应该早就能想到而没这么做吧……

- - shell最好了，只是lxk不让改写脚本。

**Comment by qq34347476** [comment]
那个是改写互助码到处宣传，然后，说脚本自己写的吧……这个换谁都不愿意……

**Comment by dockere** [comment]
> 那个是改写互助码到处宣传，然后，说脚本自己写的吧……这个换谁都不愿意……

嗯，是 啊.所以这个pr给lxk最好了
