### ISSUE TITLE
管理页面打不开怎么办，突然就登不上了

### ISSUE THREAD

**Issue by ab0880** [dockere/jd-base#55]
直接本机地址:5678就能登上，今天突然不行了

**Comment by dockere** [comment]
自己检查下原因

**Comment by ab0880** [comment]
路由器设置就可以了🤧





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dockere <notifications@github.com&gt;
发送时间: 2021年3月6日 15:55
收件人: dockere/jd-base <jd-base@noreply.github.com&gt;
抄送: ab0880 <2366926406@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dockere/jd-base] 管理页面打不开怎么办，突然就登不上了 (#55)

**Comment by ab0880** [comment]
重启容器也不行，



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dockere <notifications@github.com&gt;
发送时间: 2021年3月6日 15:55
收件人: dockere/jd-base <jd-base@noreply.github.com&gt;
抄送: ab0880 <2366926406@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dockere/jd-base] 管理页面打不开怎么办，突然就登不上了 (#55)

**Comment by ab0880** [comment]
跑起脚本来为什么显示api申请失败，qx上就没问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dockere <notifications@github.com&gt;
发送时间: 2021年3月6日 15:55
收件人: dockere/jd-base <jd-base@noreply.github.com&gt;
抄送: ab0880 <2366926406@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dockere/jd-base] 管理页面打不开怎么办，突然就登不上了 (#55)





 
自己检查下原因
