### ISSUE TITLE
运行脚本全部报错

### ISSUE THREAD

**Issue by ab0880** [dockere/jd-base#56]
🔔京东多合一签到, 开始!
您的cookie选择的是用&隔开

====================共有2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/3/7上午12:04:53=====================

"getaddrinfo ENOTFOUND raw.githubusercontent.com"
检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
文件下载异常:RequestError: connect ETIMEDOUT 60.210.18.180:443

❗️京东多合一签到, 错误!
Error: ENOENT: no such file or directory, open './JD_DailyBonus.js'
    at Object.openSync (node:fs:497:3)
    at Object.readFileSync (node:fs:393:35)
    at /jd/scripts/jd_bean_sign.js:39:28
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
另一种报错是api请求失败

**Comment by liwenzhi899** [comment]
ab0880 <notifications@github.com>于2021年3月7日 周日01:01写道：

**Comment by dockere** [comment]
github某些地区偶尔出现被墙的情况，多合一签到和yangtianxiao的抽奖机会出现偶尔下载不到的情况，解决方法:容器富强挂代理或追加raw.githubusercontent.com的hosts
