### ISSUE TITLE
py版本更新AutoSignMachine脚本失败

### ISSUE THREAD

**Issue by leiletter** [dockere/jd-base#57]
首次配置容器启动时提示失败，后运行更新命令，docker exec -it jd-py bash git_pull，仍然失败。
日志：AutoSignMachine的js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by dockere** [comment]
网络原因，检查容器是否有网，旁路由请用host模式

**Comment by leiletter** [comment]
搞定，谢谢大佬
