### ISSUE TITLE
diy.sh

### ISSUE THREAD

**Issue by is-idea** [dockere/jd-base#59]
为何偶尔会不执行

**Comment by dockere** [comment]
无图无真相

**Comment by is-idea** [comment]
大佬，情况是这样的，我在自定义脚本里写的是往sendNotify.js这个脚本里追加了一条通知信息，就是那个desp.
再我手动执行完docker exec -it jd bash git_pull命令的时候他确实生效了，但是在微信通知 ”删除失效任务通知“与“成功添加新的定时任务”这两条消息的时候，我自己自定义脚本里的改动并没有执行。是为何？

**Comment by is-idea** [comment]
![image](https://user-images.githubusercontent.com/33053444/110301161-b6e34580-8032-11eb-8f66-5414a668de3b.png)
此处并没有我自己追加的通知内容了。。。

**Comment by dockere** [comment]
可以用sed -i或perl -i修改，不过这修改没有意义呢。正常diy.sh是后执行的
