### ISSUE TITLE
是把旧版删除了拉取大佬您这个版本么？

### ISSUE THREAD

**Issue by hecarli555** [dockere/jd-base#6]
是把旧版删除了拉取大佬您这个版本么？

**Comment by dockere** [comment]
> 是把旧版删除了拉取大佬您这个版本么？

没问题；自己保留配置文件即可。

**Comment by hecarli555** [comment]
> > 是把旧版删除了拉取大佬您这个版本么？
> 
> 没问题；自己保留配置文件即可。

好的，就撑大佬你的了！

**Comment by hecarli555** [comment]
> > 是把旧版删除了拉取大佬您这个版本么？
> 
> 没问题；自己保留配置文件即可。

提示“docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.”是啥意思呢。。。？

**Comment by dockere** [comment]
> docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.

自己修改相关目录。

**Comment by hecarli555** [comment]
> > docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.
> 
> 自己修改相关目录。

怎么修改呢。。。。？小白一枚。。。是进文件夹内修改？

**Comment by dockere** [comment]
> > > docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.
> > 
> > 
> > 自己修改相关目录。
> 
> 怎么修改呢。。。。？小白一枚。。。是进文件夹内修改？

-v /你想存放的路径/jd/config:/jd/config `# 配置保存目录，冒号左边请修改为你想存放的路径` \
    -v /你想存放的路径/jd/log:/jd/log `# 日志保存目录，冒号左边请修改为你想存放的路径` \

**Comment by hecarli555** [comment]
> > > > docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.
> > > 
> > > 
> > > 自己修改相关目录。
> > 
> > 
> > 怎么修改呢。。。。？小白一枚。。。是进文件夹内修改？
> 
> -v /你想存放的路径/jd/config:/jd/config `# 配置保存目录，冒号左边请修改为你想存放的路径`
> -v /你想存放的路径/jd/log:/jd/log `# 日志保存目录，冒号左边请修改为你想存放的路径` \

感谢大佬，原来是我眼瞎没认真看路径地址，搞好了，感谢回答

**Comment by hecarli555** [comment]
> > > > docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.
> > > 
> > > 
> > > 自己修改相关目录。
> > 
> > 
> > 怎么修改呢。。。。？小白一枚。。。是进文件夹内修改？
> 
> -v /你想存放的路径/jd/config:/jd/config `# 配置保存目录，冒号左边请修改为你想存放的路径`
> -v /你想存放的路径/jd/log:/jd/log `# 日志保存目录，冒号左边请修改为你想存放的路径` \

大佬问一下，“jd_lotteryMachine”这个拉取的时候是不是有些问题？提示connect ECONNREFUSED 0.0.0.0:443

**Comment by ekonoob** [comment]
> > > > > docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.
> > > > 
> > > > 
> > > > 自己修改相关目录。
> > > 
> > > 
> > > 怎么修改呢。。。。？小白一枚。。。是进文件夹内修改？
> > 
> > 
> > -v /你想存放的路径/jd/config:/jd/config `# 配置保存目录，冒号左边请修改为你想存放的路径`
> > -v /你想存放的路径/jd/log:/jd/log `# 日志保存目录，冒号左边请修改为你想存放的路径` \
> 
> 大佬问一下，“jd_lotteryMachine”这个拉取的时候是不是有些问题？提示connect ECONNREFUSED 0.0.0.0:443
这个脚本不是LXK大佬的；你可以打开jd_lotteryMachine.js源码就能看到是LXK大佬直接下载yangtingxiao的JS后运行的，通过raw下载的方式；一般都是地区网络关系；可以通过添加hosts的方法解决；你可以使用diy.sh添加以下代码：
`Host_IP=('151.101.88.133' '151.101.228.133')
Host_Name=('raw.githubusercontent.com' 'raw.githubusercontent.com')
for (( i=0; i<=${#Host_IP[@]}; i++ )) do
echo "${Host_IP[$i]} ${Host_Name[$i]}" >> /etc/hosts
done`
或注释掉这个脚本；通过我库里/sample/diy.sh.sample模板；自己diy

**Comment by dockere** [comment]
> > > > > docker: Error response from daemon: Bind mount failed: '/root/jd/log' does not exists.
> > > > 
> > > > 
> > > > 自己修改相关目录。
> > > 
> > > 
> > > 怎么修改呢。。。。？小白一枚。。。是进文件夹内修改？
> > 
> > 
> > -v /你想存放的路径/jd/config:/jd/config `# 配置保存目录，冒号左边请修改为你想存放的路径`
> > -v /你想存放的路径/jd/log:/jd/log `# 日志保存目录，冒号左边请修改为你想存放的路径` \
> 
> 大佬问一下，“jd_lotteryMachine”这个拉取的时候是不是有些问题？提示connect ECONNREFUSED 0.0.0.0:443
>
这个脚本不是LXK大佬的；你可以打开jd_lotteryMachine.js源码就能看到是LXK大佬直接下载yangtingxiao的JS后运行的，通过raw下载的方式；一般都是地区网络关系；可以通过添加hosts的方法解决；也可以使用diy.sh添加以下代码添加hosts：
````
Host_IP=('151.101.88.133' '151.101.228.133')
Host_Name=('raw.githubusercontent.com' 'raw.githubusercontent.com')
for (( i=0; i<=${#Host_IP[@]}; i++ )) do
echo "${Host_IP[$i]} ${Host_Name[$i]}" >> /etc/hosts
done
````
或注释掉这个脚本；通过我库里/sample/diy.sh.sample模板；自己diy
