### ISSUE TITLE
环球挑战赛

### ISSUE THREAD

**Issue by qq34347476** [dockere/jd-base#61]
大佬，环球挑战赛，export_sharecodes也更新下鸭

**Comment by dockere** [comment]
更新啦。

**Comment by qq34347476** [comment]
export_sharecodes.sh里面没更新鸭！name1 name2那个……

**Comment by dockere** [comment]
> export_sharecodes.sh里面没更新鸭！name1 name2那个……

没注意，添加了额

**Comment by qq34347476** [comment]
好滴
