### ISSUE TITLE
想问下大佬镜像标签里的fil和bot分别代表什么

### ISSUE THREAD

**Issue by messysun** [dockere/jd-base#62]
如题

**Comment by dockere** [comment]
> 如题

自用的，不用理会。

**Comment by messysun** [comment]
> > 如题
> 
> 自用的，不用理会。

还有个问题就是.py镜像和.gitee镜像的shell更新貌似不同步

**Comment by kangwenhang** [comment]
本身 就不同步，看下py分支的readme

> > > 如题
> > 
> > 
> > 自用的，不用理会。
> 
> 还有个问题就是.py镜像和.gitee镜像的shell更新貌似不同步

本身 就不同步，看下py分支的readme

**Comment by messysun** [comment]
> 本身 就不同步，看下py分支的readme
> 
> > > > 如题
> > > 
> > > 
> > > 自用的，不用理会。
> > 
> > 
> > 还有个问题就是.py镜像和.gitee镜像的shell更新貌似不同步
> 
> 本身 就不同步，看下py分支的readme

感谢解答
