### ISSUE TITLE
crazy joy coin

### ISSUE THREAD

**Issue by xxyyyx** [dockere/jd-base#63]
可以加这个crazy joy合成的吗 感谢

**Comment by dockere** [comment]
不懂啥意思；-e ENABLE_WEB_PANEL=true \就是自动挂机自动合成的，24H运行并没有log

**Comment by xxyyyx** [comment]
这个-e ENABLE_WEB_PANEL=true \ 是在哪看的 自动挂机和自动合成都好像没有生效

**Comment by dockere** [comment]
> 这个-e ENABLE_WEB_PANEL=true \ 是在哪看的 自动挂机和自动合成都好像没有生效

安装的时候加这个参数就行了

**Comment by dockere** [comment]
疯狂JOY挂机脚本目前会自动合成34级JOY，

合成条件如下：

当存在8个34级JOY，并且剩余金币大于等于6Q，则此条件下合并两个34级JOY

即可为后面继续合成两只新的34级JOY(按全部用30级JOY合成一只34级JOY计算需:166T * 2 * 2 * 2 * 2 = 2.6Q * 2(两只34级JOY) = 5.2Q，取6Q)时,

**Comment by dockere** [comment]
查看挂机脚本日志
docker exec -it jd pm2 monit`或`docker exec -it jd pm2 logs

**Comment by xxyyyx** [comment]
进程好像是空的 
![CD6Q3ZSE4AWUAO@EAEVCURF](https://user-images.githubusercontent.com/42132468/110340896-bb285680-8064-11eb-88d2-9990975bd55d.png)
是用的shell一键安装那个

**Comment by dockere** [comment]
第一次因为没有cookie，所以不会启动；请写入cookie后重启容器

**Comment by xxyyyx** [comment]
感谢 应该跑起来了
