### ISSUE TITLE
求教如何设置PY镜像内置的xmly推送

### ISSUE THREAD

**Issue by qaz88q11** [dockere/jd-base#67]
以在JD内添加额外变量export SCKEY="XXXXXXXXXX"但还是不能推送，求大佬帮助

**Comment by kangwenhang** [comment]
原作者取消了server酱的推送，可以使用bark或者tg推送

**Comment by kangwenhang** [comment]
试试bark跟tg推送

**Comment by qaz88q11** [comment]
实在是搞不定，严重怀疑是这个镜像的问题！希望老大能更换whyour带提现功能的镜像
