### ISSUE TITLE
docker里面除了jd部分的东西怎么运行的？

### ISSUE THREAD

**Issue by sofs2005** [dockere/jd-base#70]
我只要设置好配置文件就可以了吗？cron里面要加吗？能不能看到日志啊

**Comment by dockere** [comment]
不要jd,jr开头的js脚本就行。同样有日志的

**Comment by landcruser** [comment]
> 不要jd,jr开头的js脚本就行。同样有日志的

大佬，换了原作者的docker镜像，xmly的py和autosignmachine还能用吗？看他的文件定义貌似没有拉取代码的文件夹啊

**Comment by dockere** [comment]
> > 不要jd,jr开头的js脚本就行。同样有日志的
> 
> 大佬，换了原作者的docker镜像，xmly的py和autosignmachine还能用吗？看他的文件定义貌似没有拉取代码的文件夹啊

没有，需要python

**Comment by sofs2005** [comment]
> 不要jd,jr开头的js脚本就行。同样有日志的

可能我没说清楚，我问的是那几个联通、爱奇艺什么的签到，配置好了会自动跑吗？还是要加cron的？具体是哪几个啊，我昨天改了配置今天看好像没跑

**Comment by dockere** [comment]
> > 不要jd,jr开头的js脚本就行。同样有日志的
> 
> 可能我没说清楚，我问的是那几个联通、爱奇艺什么的签到，配置好了会自动跑吗？还是要加cron的？具体是哪几个啊，我昨天改了配置今天看好像没跑

会的，自己添加cron就行了，比如我把需要运行test目录下的test.py并写入log，可以这么写，你把crontab.list想象成一个可以定时执行shell的终端就很好理解了。联通这些该如何执行自己研究吧。
10 0 * * * python3 /jd/scripts/test/test.py >> ${JD_DIR}/log/test/$(date +\%Y-\%m-\%d-\%H-\%M-\%S).log 2>&1

**Comment by dockere** [comment]
*/30 4-23 * * * node /jd/scripts/AutoSignMachine/index.js unicom --user ** ***password *** 
大概就是这样了，具体github搜下AutoSignMachine项目

**Comment by dockere** [comment]
> */30 4-23 * * * node /jd/scripts/AutoSignMachine/index.js unicom --user ** *** -- password ***
> 大概就是这样了，具体github搜下AutoSignMachine项目

**Comment by sofs2005** [comment]
> */30 4-23 * * * node /jd/scripts/AutoSignMachine/index.js unicom --user ** *** -- password ***
> 
> 大概就是这样了，具体github搜下AutoSignMachine项目

好像不行嘛，运行了也没效果，那几个json格式的命令好像也不好使

**Comment by dockere** [comment]
🤭自己研究吧！我正常的

**Comment by landcruser** [comment]
> > > 不要jd,jr开头的js脚本就行。同样有日志的
> > 
> > 
> > 大佬，换了原作者的docker镜像，xmly的py和autosignmachine还能用吗？看他的文件定义貌似没有拉取代码的文件夹啊
> 
> 没有，需要python

谢谢
