### ISSUE TITLE
config.sh.sample版本是否需要更新了？

### ISSUE THREAD

**Issue by photonmang** [dockere/jd-base#71]
我看lxk的config.sh.sample版本已经更新了，我们这个容器一直没有更新呢

**Comment by dockere** [comment]
就一个TG反代的变量，其实自己加了，只是没有发通知

**Comment by reman-l** [comment]
教程后面写的使用方法是填：https://xxxxx.xxx.workers.dev/bot888518123:AAERbtbJ5BnO3Ngyx5Xti1lTsGFgv1TRbh4/sendMessage?chat_id=703019123&text=123，实际是填这整个
还是只填：xxxxx.xxx.workers.dev，然后TG的BOT和ID，依然是在之前填的位置不变呢

**Comment by dockere** [comment]
这个具体自己研究吧，lxk添加的变量，我也没用过
