### ISSUE TITLE
增加自定义脚本后，是否可以在config.sh中增加环境变量？

### ISSUE THREAD

**Issue by photonmang** [dockere/jd-base#72]
自定义脚本中，可以对自定义下载过来的脚本进行环境变量吗？
如果可以的话，需要怎么写呢？

**Comment by dockere** [comment]
不知道你指的环境变量是哪一个；git_pull.sh定义的变量可以直接调用，例如：FileDiy，如需要自己定义变量；可以直接定义在diy.sh里。

**Comment by dockere** [comment]
################################## 额外的环境变量（选填） ##################################
## 请在以下补充你需要用到的额外的环境变量，形式：export 变量名="变量值"

**Comment by photonmang** [comment]
> ################################## 额外的环境变量（选填） ##################################
> 
> ## 请在以下补充你需要用到的额外的环境变量，形式：export 变量名="变量值"

感谢大佬解惑，谢谢！
