### ISSUE TITLE
如何添加自定义脚本

### ISSUE THREAD

**Issue by googooog** [dockere/jd-base#73]
例如联通签到

我需要在diy.sh里直接填入脚本地址，然后在crontab.list里设定时间就可以了么？

cookie需要这么填入？

谢谢大佬解答

**Comment by dockere** [comment]
*/30 4-23 * * * node /jd/scripts/AutoSignMachine/index.js unicom --user ** *** 
差不多就是这样了，你把crontab.list理解成一个可以定时的终端就行了，联通的具体自己琢磨。
