### ISSUE TITLE
提示未提供助力码

### ISSUE THREAD

**Issue by yks176175** [dockere/jd-base#77]
![Screenshot_20210317-112004](https://user-images.githubusercontent.com/67717024/111409985-e0772d80-8712-11eb-8d6d-bf40ab9fac25.png)
## 在panel里填写了助力码，跑脚本显示未提供

**Comment by dockere** [comment]
填在config.sh对应互助区域

**Comment by yks176175** [comment]
![image](https://user-images.githubusercontent.com/67717024/111413302-f851b000-8718-11eb-876e-1643fcaf74c2.png)
我都有填

**Comment by dockere** [comment]
下面也要啊，谁互助谁。具体拉到最下面查看使用方法。

**Comment by yks176175** [comment]
ok 谢谢
