### ISSUE TITLE
惊喜农场的任务出错是lxk大佬的问题吗？

### ISSUE THREAD

**Issue by UMRQWQ** [dockere/jd-base#78]
我看lxk的脚本加密了，不太懂，日志出来https://tu.yaohuo.me/imgs/2021/03/7f21a5d810624699.png   这样

**Comment by dockere** [comment]
这活动基本可以放弃了。毛小毛病多，lxk也不想修了，建议注释。

**Comment by happysoul** [comment]
不建议碰京喜的脚本，黑号风险严重，新号很快就什么活动都参与不了，估计2个团队，jx 风险控制做的太好了。。。
“活动太火爆了，请稍后再试”

**Comment by dockere** [comment]
> 不建议碰京喜的脚本，黑号风险严重，新号很快就什么活动都参与不了，估计2个团队，jx 风险控制做的太好了。。。
> “活动太火爆了，请稍后再试”

嗯。建议注释

**Comment by UMRQWQ** [comment]
现在又好了，又不报错了
