### ISSUE TITLE
大佬，能出个 版本更新同步的 sh 和  远程 diy.sh 的 地方或者教程嘛

### ISSUE THREAD

**Issue by qq34347476** [dockere/jd-base#8]
能不能出个 版本更新的命令，  远程 diy 的使用说明啊
那个参考 更新版本的 文档打不开   ---  如需更新，请参考WIKI（https://github.com/EvineDeng/jd-base/wiki）中"如何更新配置文件"部分的操作说明，进行智能比对后修改。
谢谢

**Comment by dockere** [comment]
> 能不能出个 版本更新的命令， 远程 diy 的使用说明啊
> 那个参考 更新版本的 文档打不开 --- 如需更新，请参考WIKI（[https://github.com/EvineDeng/jd-base/wiki）中"如何更新配置文件"部分的操作说明，进行智能比对后修改。](https://github.com/EvineDeng/jd-base/wiki%EF%BC%89%E4%B8%AD%22%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%22%E9%83%A8%E5%88%86%E7%9A%84%E6%93%8D%E4%BD%9C%E8%AF%B4%E6%98%8E%EF%BC%8C%E8%BF%9B%E8%A1%8C%E6%99%BA%E8%83%BD%E6%AF%94%E5%AF%B9%E5%90%8E%E4%BF%AE%E6%94%B9%E3%80%82)
> 谢谢

配置文件用对比工具更新就行了；刚更新个diy.sh的模板；请更新后查看说明。

**Comment by qq34347476** [comment]
还有个不太清楚的地方想请教下，这个互助码，是要手动填写吗，还是用docker跑的都会 相互 互助？

**Comment by dockere** [comment]
> 还有个不太清楚的地方想请教下，这个互助码，是要手动填写吗，还是用docker跑的都会 相互 互助？

有的脚本会相互互助；有的不会，需要自己填写互助码，填写方式请参照配置文件config.sh配置文件最下方的使用说明

**Comment by qq34347476** [comment]
能不能再请教下： 
我写了个格式化成 使用说明的 获取所有互助码的 脚本， 我怎么能把这个弄成自动填到配置文件
https://gitee.com/qq34347476/quantumult-x/raw/master/format_share_jd_code.js
是不是目前只能跑完自己粘贴过去？

**Comment by dockere** [comment]
> 能不能再请教下：
> 我写了个格式化成 使用说明的 获取所有互助码的 脚本， 我怎么能把这个弄成自动填到配置文件
> https://gitee.com/qq34347476/quantumult-x/raw/master/format_share_jd_code.js
> 是不是目前只能跑完自己粘贴过去？

使用diy.sh模板就行了；然后在日志查询查看运行日志。
https://raw.githubusercontent.com/dockere/jd-base/master/sample/diy.sh
