### ISSUE TITLE
大佬请教个问题

### ISSUE THREAD

**Issue by ling157** [dockere/jd-base#80]
用您的镜像和E大的镜像都出现这问题，该怎么解决？
昨天推送还好好的，今天就这样了
![QQ图片20210317172602](https://user-images.githubusercontent.com/80083389/111445132-0e299a00-8746-11eb-9fde-493a378b9b5a.png)

**Comment by dockere** [comment]
检查下代理看看

**Comment by ling157** [comment]
> 检查下代理看看

像京豆变动正常推送，就农场和萌宠就这样，推送时出错了。
