### ISSUE TITLE
bark推送异常报错

### ISSUE THREAD

**Issue by happysoul** [dockere/jd-base#82]
拉取 noobx/jd:gitee 至少运行了半个月了 config.sh 更新过 里面显示是 Version: v3.30.6 
昨天开始只运行没有bark推送了，可以确认bark正常，可以接其他程序运行的推送
查看log文件夹下日志，程序运行正常只是没有推送，发现推送报错 日志

`Bark APP发送通知调用API失败！！

HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: undefined,
  timings: {
    start: 1616029840081,
    socket: 1616029840081,
    lookup: 1616029840094,
    connect: 1616029840134,
    secureConnect: 1616029840219,
    upload: 1616029840219,
    response: 1616029840260,
    end: 1616029840261,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 13,
      tcp: 40,
      tls: 85,
      request: 0,
      firstByte: 41,
      download: 1,
      total: 180
    }
  }
}`

现在切到方糖推送了
不清楚这个是lxk的js脚本问题还是docker调用发送shell的问题

**Comment by dockere** [comment]
你几个号？运行的什么脚本

**Comment by happysoul** [comment]
> 你几个号？运行的什么脚本

6个号 虽说发送内容大 但之前一直没问题 突然发送报错 有点怀疑是bark的问题，最近几天bark发送其他消息也有失败的 看日志估计跟转码有关  还没具体看问题。

**Comment by popsee** [comment]
bark 推送消息限制很短，我测试大于2KB以上的字符就完蛋了，出现同错——Request Header Fields Too Large，改成server酱推送则完全没问题，感觉是bark限制了推送内容大小。
解决方案：建议要么精简推送消息，要么换成server酱！

**Comment by fengmikaelson** [comment]
> > bark 推送消息限制很短，我测试大于2KB以上的字符就完蛋了，出现同错——Request Header Fields Too Large，改成server酱推送则完全没问题，感觉是bark限制了推送内容大小。
> > 解决方案：建议要么精简推送消息，要么换成server酱！
> 
> 不是bark的问题，是ios的推送限制，必须小于4k，bark推送的时候貌似用的是gbk，3字节存储一个汉字，我测试了1360个汉字以上会被拦截（大概是 4096/3=1365.33）。如果是4000以内的ascII字符能推送成功，多了就报错

后来怎么解决？

**Comment by happysoul** [comment]
> > > bark 推送消息限制很短，我测试大于2KB以上的字符就完蛋了，出现同错——Request Header Fields Too Large，改成server酱推送则完全没问题，感觉是bark限制了推送内容大小。
> > > 解决方案：建议要么精简推送消息，要么换成server酱！
> > 
> > 
> > 不是bark的问题，是ios的推送限制，必须小于4k，bark推送的时候貌似用的是gbk，3字节存储一个汉字，我测试了1360个汉字以上会被拦截（大概是 4096/3=1365.33）。如果是4000以内的ascII字符能推送成功，多了就报错
> 
> 后来怎么解决？

这种ios推送限制没办法解决啊，他就只让你用4k数据，要不就考虑把内容减少了。每天的 资产变动通知 账号少的修改配置使用精简内容推送，对于一个docker 里5个账号以上的，就只能用server酱等其他的看，或者不看，你也可以自己写个python等脚本截取log日志内容定时拆分推送。
