### ISSUE TITLE
有没有不填互助码 让他们自动互相助力的办法

### ISSUE THREAD

**Issue by nick814** [dockere/jd-base#83]
我看lkx大佬3.9号更新了个 能不用在去填互助了，自动去读输出的助力码，这个有没有地方也有这个功能啊 整理互助太累了

**Comment by dockere** [comment]
没有，lxk的docker1也不错，可以试试

**Comment by nick814** [comment]
> 没有，lxk的docker1也不错，可以试试

我看了那个  我是想最好弄 先给我的主力账户助力，然后助力好了，在工具人互相助力， lxk那个有个不太好  3.9号那个如果使用了自动助力，没有优先级设置，这样到时候工具人相互助力好了  没次数了 那样就不方便了

**Comment by dockere** [comment]
> > 没有，lxk的docker1也不错，可以试试
> 
> 我看了那个 我是想最好弄 先给我的主力账户助力，然后助力好了，在工具人互相助力， lxk那个有个不太好 3.9号那个如果使用了自动助力，没有优先级设置，这样到时候工具人相互助力好了 没次数了 那样就不方便了

填写好一次就可以了；一劳永逸

**Comment by nick814** [comment]
> > > 没有，lxk的docker1也不错，可以试试
> > 
> > 
> > 我看了那个 我是想最好弄 先给我的主力账户助力，然后助力好了，在工具人互相助力， lxk那个有个不太好 3.9号那个如果使用了自动助力，没有优先级设置，这样到时候工具人相互助力好了 没次数了 那样就不方便了
> 
> 填写好一次就可以了；一劳永逸

我同事都让我帮他们挂的  我手里20多个号  填过去人受不了 哈哈

**Comment by dockere** [comment]
-_-

**Comment by UMRQWQ** [comment]
有脚本可以生成互助码助力的规则的

**Comment by hong0980** [comment]
> 有脚本可以生成互助码助力的规则的

导出后复制过去很简单，要是弄个脚本自己覆盖那还要快

**Comment by Aexus** [comment]
> 有脚本可以生成互助码助力的规则的

能否分享下,谢谢
