### ISSUE TITLE
pushplus 停止推送服务

### ISSUE THREAD

**Issue by googooog** [dockere/jd-base#85]
https://mp.weixin.qq.com/s/XbWih4Mv5ggBPGg0-QBJJw

之前的http://pushplus.hxtrip.com/ 要停止维护了

大佬是否可以改为 http://www.pushplus.plus/推送呢？

我看lxk0301的docker已经改为 http://www.pushplus.plus/推送了

**Comment by dockere** [comment]
变量不变，自己去新的地方重新注册填上即可。
