### ISSUE TITLE
检测配置文件版本貌似有点问题

### ISSUE THREAD

**Issue by wxjbb** [dockere/jd-base#88]
已经很久没有收到配置文件更新的推送了（ps：定时任务新增和删除的推送是正常的），刚刚看了一下代码，发现需要send_count这个文件，然后进容器里看了一下好像没有这个文件存在，猜测是不是这个原因导致的（不是很懂shell，大佬能帮忙看看哪里有问题吗）。
`## 检测配置文件版本
function Notify_Version {
  [ -f "${SendCount}" ] && [[ $(cat ${SendCount}) != ${VerConfSample} ]] && rm -f ${SendCount}
  UpdateDate=$(grep " Date: " ${FileConfSample} | awk -F ": " '{print $2}')
  UpdateContent=$(grep " Update Content: " ${FileConfSample} | awk -F ": " '{print $2}')
  if [ -f ${FileConf} ] && [[ "${VerConf}" != "${VerConfSample}" ]] && [[ ${UpdateDate} == $(date "+%Y-%m-%d") ]]
  then
    if [ ! -f ${SendCount} ]; then
      echo -e "检测到配置文件config.sh.sample有更新\n\n更新日期: ${UpdateDate}\n当前版本: ${VerConf}\n新的版本: ${VerConfSample}\n更新内容: ${UpdateContent}\n如需使用新功能请对照config.sh.sample，将相关新参数手动增加到你自己的config.sh中，否则请无视本消息。\n" | tee ${ContentVersion}
      echo -e "本消息只在该新版本配置文件更新当天发送一次。" >> ${ContentVersion}
      cd ${ShellDir}
      node update.js
      if [ $? -eq 0 ]; then
        echo "${VerConfSample}" > ${SendCount}
        [ -f ${ContentVersion} ] && rm -f ${ContentVersion}
      fi
    fi
  else
    [ -f ${ContentVersion} ] && rm -f ${ContentVersion}
    [ -f ${SendCount} ] && rm -f ${SendCount}
  fi
}`

**Comment by dockere** [comment]
没有收到，就是没有更新呀！😂

**Comment by wxjbb** [comment]
今天明明已经从v3.30.6升级到v3.31.6了，这样也没有通知，正常吗？

**Comment by dockere** [comment]
哦；晚点我看看。

**Comment by wxjbb** [comment]
好的，谢谢大佬

**Comment by chenkid999** [comment]
我一直以为是我的问题，原来都是这样

**Comment by wxjbb** [comment]
> 我一直以为是我的问题，原来都是这样

原来不止我一个人这样啊

**Comment by dockere** [comment]
已解决
