### ISSUE TITLE
crontab.list 文件78行代码有问题

### ISSUE THREAD

**Issue by cuxevip** [dockere/jd-base#89]
414 7,12,19 * * * bash /home/jd/jd.sh jd_beauty
最前面的是分钟(0-59)，这里414，怎么回事？而且这分钟数四百多一直在变，麻烦修改一下，谢谢！
![IMG_20210321_003013](https://user-images.githubusercontent.com/30213648/111877349-f97d1a00-8970-11eb-8741-a8ba875967ef.jpg)

**Comment by cuxevip** [comment]
> 414 7,12,19 * * * bash /home/jd/jd.sh jd_beauty
> 最前面的是分钟(0-59)，这里414，怎么回事？而且这分钟数四百多一直在变，麻烦修改一下，谢谢！

![Uploading IMG_20210321_003013.jpg…]()

**Comment by dockere** [comment]
好了

**Comment by cuxevip** [comment]
> 好了，手动改回去就可以了

脚本一同步，又变四百多了，这样的话，每小时都要修改一次，挺麻烦的，还是麻烦你修改一下远端的脚本吧

**Comment by dockere** [comment]
早修复这问题了；也不知道你这是哪个远古版本

**Comment by flyinfox** [comment]
我的是418，昨天才安装的，用脚本安的

**Comment by bao3** [comment]
`19 7,12,19 * * * bash jd jd_beauty`
我的整个文件也不到 78行，你说的这个定时脚本是在我的 65 行。而且跟你的不一样。。。我没有改过任何东西，从来是默认的。提供参考。
