### ISSUE TITLE
你好，如何更新镜像

### ISSUE THREAD

**Issue by cccp173** [dockere/jd-base#90]
如题

**Comment by cccp173** [comment]
我看对比sample最新版本都到31了我的还在30😂

**Comment by dockere** [comment]
对比工具，不一样的中间有个">"箭头，点一下就对比过去了，也可以手动复制过去，配置文件不是自动更新的

**Comment by cccp173** [comment]
好的谢谢大佬解答

**Comment by cccp173** [comment]
还有大佬，麻烦再问一个问题，宠汪汪之前都会自动用积分兑京豆，但最近宠汪汪不会自动兑换京豆了，这是怎么回事
