### ISSUE TITLE
为什么脚本没有自动推送了？

### ISSUE THREAD

**Issue by photonmang** [dockere/jd-base#92]
我看到昨天就更新了城城分现金的脚本，但是只有config.sh.sample更新了。而脚本反而没有更新，找不到这个脚本，这是怎么回事？

**Comment by kangwenhang** [comment]
你再找找，有的

**Comment by photonmang** [comment]
> 你再找找，有的

真没有，而且执行容器更新，还提示错误。。

**Comment by kangwenhang** [comment]
> > 你再找找，有的
> 
> 真没有，而且执行容器更新，还提示错误。。

贴图看看是什么报错

**Comment by photonmang** [comment]
> > > 你再找找，有的
> > 
> > 
> > 真没有，而且执行容器更新，还提示错误。。
> 
> 贴图看看是什么报错

docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "4e791e9f188f80506ca3f10e1e7346236a3533e71912d0af423028f0c6adcda6". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by photonmang** [comment]
> > > 你再找找，有的
> > 
> > 
> > 真没有，而且执行容器更新，还提示错误。。
> 
> 贴图看看是什么报错

Fetching origin
Handshake: Repository more than 5 connections.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at ebea952 default_task.sh update

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by photonmang** [comment]
重启了下watchtower容器，再次执行更新，出现：
Fetching origin
HEAD is now at ebea952 default_task.sh update

**Comment by kangwenhang** [comment]
> > > > 你再找找，有的
> > > 
> > > 
> > > 真没有，而且执行容器更新，还提示错误。。
> > 
> > 
> > 贴图看看是什么报错
> 
> Fetching origin
> Handshake: Repository more than 5 connections.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> error: Could not fetch origin
> HEAD is now at ebea952 default_task.sh update
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...

被限制链接了 （如在拉取活动脚本时失败提示 Repository more than 5 connections 是由于 Gitee 限制了每秒同时拉取项目的IP不能超过 5 个所导致，此报错为正常现象，重新执行更新命令即可。）

**Comment by kangwenhang** [comment]
> 重启了下watchtower容器，再次执行更新，出现：
> Fetching origin
> HEAD is now at ebea952 default_task.sh update

watchtower是更新镜像的，跟更新脚本没有任何关系

**Comment by photonmang** [comment]
> > 重启了下watchtower容器，再次执行更新，出现：
> > Fetching origin
> > HEAD is now at ebea952 default_task.sh update
> 
> watchtower是更新镜像的，跟更新脚本没有任何关系

更新到脚本了。。谢谢~~
