### ISSUE TITLE
控制台没有扫描登录了

### ISSUE THREAD

**Issue by JiZhi-Error** [dockere/jd-base#93]
![image](https://user-images.githubusercontent.com/24365406/111935496-8bfef400-8afe-11eb-978b-c87f4120af53.png)

**Comment by JiZhi-Error** [comment]
我记得以前在首页这里能扫码登录

**Comment by dockere** [comment]
离家出走了

**Comment by JiZhi-Error** [comment]
> 离家出走了

啥时候给这逆子找回来

**Comment by vale8023** [comment]
啥时候回来😭

**Comment by bao3** [comment]
刚好我的 cookie 到期了，现在不能扫码了。。。

**Comment by AmazingZ-sys** [comment]
我的 cookie 今天到期，突然发现不能扫码登录了

**Comment by dockere** [comment]
我的 cookie 今天到期，突然发现不能扫码登录了

**Comment by Liquid-w** [comment]
可以执行 node getJDCookie.js 然后将得到的信息，然后在二维码转换网站上转为二维码

**Comment by dockere** [comment]
> 可以执行 node getJDCookie.js 然后将得到的信息，然后在二维码转换网站上转为二维码

谢谢！

**Comment by lfy0425** [comment]
可以告知一下具体怎么操作不？node getJDCookie.js不会用

**Comment by ekonoob** [comment]
终端执行：docker exec -it jd bash jd getJDCookie now

**Comment by dockere** [comment]
终端执行：docker exec -it jd bash jd getJDCookie now
