### ISSUE TITLE
xmly问题

### ISSUE THREAD

**Issue by landcruser** [dockere/jd-base#95]
大佬们，你们的xmly还正常吗？我的显示设备异常

**Comment by Tivon521** [comment]
黑了，没救了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: landcruser ***@***.***&gt;
发送时间: 2021年3月23日 18:47
收件人: dockere/jd-base ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[dockere/jd-base] xmly问题 (#95)





 
大佬们，你们的xmly还正常吗？我的显示设备异常

**Comment by dockere** [comment]
giao
