### ISSUE TITLE
更新脚本提示错误，访问被拒绝了。

### ISSUE THREAD

**Issue by photonmang** [dockere/jd-base#97]
Fetching origin
Access deined: DeployKey not enabled
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at 29433ea SCF remove jd_speed_redpocke

**Comment by gys619** [comment]
跑路了，把更新注释了吧，不要重启容器

**Comment by photonmang** [comment]
> 跑路了，把更新注释了吧，不要重启容器

啊？这么快删库了吗？我刚刚重启了下容器，原来脚本会被自动删掉么？

**Comment by gys619** [comment]
可能没了吧。。大佬暂时休息

**Comment by qaz88q11** [comment]
L大删掉密钥了，目前谁也更新不了

**Comment by dockere** [comment]
更新镜像

**Comment by 282206796** [comment]
> 更新镜像

如何更新呢
